### ISSUE TITLE
Dropdown menu for Quests and Badges

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1010]
Carve off the right side of the Quests and Badges buttons in the left menu, and place drop down menus there:
![image](https://user-images.githubusercontent.com/10604391/172280264-a9d442d2-158d-405e-a30c-bb5c46b43500.png)

Content for now:

Quests drop down menu items:
- In Progress (students)
- Completed (students)
- Drafts (contextual, if they have a drafts tab - TAs and staff)
- Campaigns (staff)
- Common quest info (staff)

Badges drop down menu items:
- Badge Types (staff)

**Comment by tylerecouture** [comment]
Consider replacing current logic and styling to use bootstrap Split button dropdown:
https://getbootstrap.com/docs/3.3/components/#btn-dropdowns-split

**Comment by 9921622** [comment]
Need to also add link for CommonData

from #1072:
```
Maybe rename to "Common Quest Info"?

Place link to List view in drop down menu from https://github.com/bytedeck/bytedeck/issues/1010
```
