### ISSUE TITLE
Javascript Enabled Through Student Submission

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1022]
I have a student that is into hacking. He was able to introduce some JavaScript into a button. See his submission [here](https://studiotyee.bytedeck.com/quests/submission/30670/).

JavaScript was disabled and the app automatically remove scripts. Is this an issue for the app?

**Comment by tylerecouture** [comment]
HTML should be escaped completely from "quick comments" form.  Currently you can enter comments in the 
![Screenshot-16](https://user-images.githubusercontent.com/10604391/233675822-b6d841aa-3d76-4f62-956a-c586400c34c2.png)
