### ISSUE TITLE
form data generating utility method for tests

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1048]
See https://github.com/bytedeck/bytedeck/pull/1034#discussion_r900700960

Refactor this method so we can use it in any simple form or form view when we need form data!  Not sure where it should go, maybe same place I put the other test utility methods like AdminRedirect etc?

**Comment by 9921622** [comment]
mislinked a different issue instead of this one. Because of pr #1050, this issue should be closed
