### ISSUE TITLE
Remove "Series" from badge form

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1052]
This "Series" field isn't currently used and should be removed from the badge create and update form.

It's an optional field, so it can be left on the model, we'll just ignore it and pretend it doesn't exist for now. 

Its use case will probably be replaced by Tags #960 

![image](https://user-images.githubusercontent.com/10604391/175841096-b07dc516-3ca4-4260-849d-67d67aa97a12.png)

**Comment by Dylan-RG-Patterson** [comment]
it looks like this issue's already been addressed. 
![image](https://user-images.githubusercontent.com/105619909/180118169-ef2b4f12-181e-461b-8425-1efc7bba8be0.png)
![image](https://user-images.githubusercontent.com/105619909/180118226-5d664972-5bbe-49b9-8b51-ae7aed95e454.png)
