### ISSUE TITLE
Ajax add new submissions for approval

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#111]
Run every minute or so to prevent need to refresh approvals page for teachers

**Comment by tylerecouture** [comment]
This is almost completed, in `src/templates/javascript.html`

But the function `ajaxApprovalsBadge()` method should only run for staff members, not all users.  Wrap in some django template tags?

**Comment by yujinyuz** [comment]
It seems that there's already one for that 

https://github.com/bytedeck/bytedeck/blob/61dc43131ac75d57936b897c510e1b9df05412b3/src/templates/javascript.html#L126-L129

**Comment by tylerecouture** [comment]
Haha!
