### ISSUE TITLE
Tags CRUD view completion

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1120]
There are basic CRUD views already I think, but a create view is missing. Currently Tags are created directly by adding them via the quest or badge form.

Also missing is an edit view. There should be the ability to edit the name of a tag from the lost view (just like all our other CRUD lost views)

Finally a delete tag button with confirmation page (confirmation page lists all items that will lose the tag of deleted, similar to tag detail view)

Admin buttons on right of the list view table, just like other list views.

**Comment by 9921622** [comment]
should be closed?

**Comment by tylerecouture** [comment]
Yep, thank you.
