### ISSUE TITLE
Fix some page icons

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1132]
Campaign Views = Compass
Courses Views = Book (like in the admin dropdown)

See the various course views for how to use a different icon in the templates (Courses, Ranks, Semesters, Blocks all have different icons from same app). Will need to do something similar for campaigns (Category in the quest_manager app)

**Comment by owolabi250** [comment]
i will love to work on this project. can you put me through?

**Comment by tylerecouture** [comment]
Yes! Go ahead and try to fix this issue. Can I ask how you found this repo?

**Comment by Dylan-RG-Patterson** [comment]
Is this issue still being contributed to? I'd be happy to fix it.
