### ISSUE TITLE
Build errors & warnings

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1136]
`docker-compose build` results in a few errors/warnings

1. Why is it complaining about an old pip when this command is already in the dockerfile? `RUN python3 -m pip install --upgrade pip`
2. need to resolve that pip dependancy resolver error.
3. is there an easy way to suppress the "Running pip as root" warning? This is in a container, so we don't need a venv... it IS our venv

![image](https://user-images.githubusercontent.com/10604391/183570249-4141d0a7-cb4d-420d-8f20-c4150094ae6b.png)

**Comment by 9921622** [comment]
couldn't recreate the error or warning despite clearing all containers/starting from scratch.
using both ```docker compose build``` and ```docker-compose build``` (also im on Windows)

I dont get warnings only errors. might be possible your docker is outdated

warning messages
```
time="2024-06-04T16:19:04-07:00" level=warning msg="D:\\#\\BYTEDECK_FORK\\bytedeck\\docker-compose.yml: `version` is obsolete"
time="2024-06-04T16:19:04-07:00" level=warning msg="D:\\#\\BYTEDECK_FORK\\bytedeck\\docker-compose.override.yml: `version` is obsolete"
```

**Comment by tylerecouture** [comment]
This is ancient and if you can't reproduce, I'll close it and assume it's fixed itself or was a problem with old dependencies or other software in our stack.
