### ISSUE TITLE
Remove empty p tags in tag detail view

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1147]
- [ ] Make everything after the tag name in the heading` <small>`

![image](https://user-images.githubusercontent.com/10604391/183817551-a8f309e3-79b5-445e-9d8c-209f18569481.png)

- [ ] Remove the empty `<p>` tags above badge and quest lists.

![image](https://user-images.githubusercontent.com/10604391/183817125-a2a4bd82-3f18-4656-b074-08398e9e3679.png)

**Comment by hoyeen01** [comment]
Hello 
this is my first attempt contributing to open  source
I'd like to fix this issue.

**Comment by tylerecouture** [comment]
@hoyeen01 That's great!  Please go ahead and try it!  Can I ask how/why you found this repo?

**Comment by xscottxbrownx** [comment]
I found it on https://goodfirstissues.com/

**Comment by tylerecouture** [comment]
Woah thanks! I'd never heard of that before.  Did you learn about that from a coding course / instructor?
