### ISSUE TITLE
Tags to Visual Representation

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1155]
![Tags Chart mockup](https://user-images.githubusercontent.com/95307054/184032514-1e43e66c-8400-4544-a3cd-50d3a7585fe4.png)!
In this case, the tags are related to math skills or learning outcomes.

**Comment by tylerecouture** [comment]
The project already uses [django-jchart](https://github.com/matthisk/django-jchart) for the graphs on the Mark Calculations Page, however this is a stale library, so I'm open to something newer/better/more widely supported.  Even direct use of [chart.js](https://www.chartjs.org/)

The methods should already exist to get this data for a student, it's just a matter of creating a place to present the data!

I think for now, a link beside the "XP by Tag" heading in the profile to go to this new view.

**Comment by aluxenburg** [comment]
I am excited about this. When are you planning to push this out?
