### ISSUE TITLE
Active Deck Monitoring in Tenant List

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1160]
In the list which comes up in the Tenant List of Decks in the Admin Deck, I am trying to organize the list for monitoring and contact with deck owners.
It would be great to have a column for "last active date".
Also, if possible, it would be nice to be able to filter the list by "Active User Count" as you have with the other columns... this gives me a sense of who is (or was) actually using the deck.

**Comment by tylerecouture** [comment]
This should be super easy to add.

One question: what do we use for "last active" date?  Last time anyone logged in? Last time a teacher logged in? Last time the owner logged in? Something else?

**Comment by aluxenburg** [comment]
I guess last time the teacher logged in would let me know if the deck is active or if I should archive it somehow.

**Comment by tylerecouture** [comment]
I figured out how to make some sections highlight.  As a first go, I made the users highlight if active users is too high:

![image](https://user-images.githubusercontent.com/10604391/184568359-e1a8fe09-fdc2-4d9d-aa00-7d80b96c0e25.png)

**Comment by aluxenburg** [comment]
Ahh... I was wondering what that was. I asked in spaces before I saw this.  Great idea. I guess I should ask my questions here rather than in spaces? Should I move them over here?
