### ISSUE TITLE
Make generate_content a management command

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1163]
Currently you have to go into the shell and run it from the django python shell (see instructions here)
https://github.com/bytedeck/bytedeck#installing-more-sample-data

Create a new management command that allows developers to run this directly from manage.py:

https://docs.djangoproject.com/en/4.1/howto/custom-management-commands/

**Comment by 9921622** [comment]
@tylerecouture 
what does ```num_campaigns``` in ```generate_quests``` even do?
It doesn't look like it makes any new campaigns.

![image](https://github.com/bytedeck/bytedeck/assets/39788517/699cbe8e-4555-4253-b3d0-5a4d60bfc1ac)

**Comment by 9921622** [comment]
nvm its mentioned here: 

https://github.com/bytedeck/bytedeck/issues/1014
