### ISSUE TITLE
Top of subscription page still has lorem ipsum text

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1169]
https://bytedeck.com/pages/subscribe/

**Comment by tylerecouture** [comment]
@aluxenburg What do you want to put there?

**Comment by aluxenburg** [comment]
I'll think about it and respond here.

**Comment by aluxenburg** [comment]
We are a non-profit learning society. Our subscription pricing is competitive and funds are only utilized for maintaining systems and development. The board members are volunteers, and put many hours into running and further developing Bytedeck. Thank you for subscribing. Please let us know how we might serve you better. 

What do you think?

**Comment by tylerecouture** [comment]
Fixed.
