### ISSUE TITLE
export tenant list for emails

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1170]
As is I would have to copy and paste each email... yuck.
Was just about to send email to all... but will wait.  Can you export somehow?

**Comment by aluxenburg** [comment]
I copied the whole page and pasted to a google sheet and was able to get it that way.  Sorry about the PRIORITY call.... just move that to whenever

**Comment by tylerecouture** [comment]
Add an admin action to render comma separated list of selected tenant's email addresses

**Comment by tylerecouture** [comment]
This might be even better:

https://stackoverflow.com/questions/18619577/using-django-admin-actions-to-send-bulk-emails

**Comment by tylerecouture** [comment]
See #1386
