### ISSUE TITLE
Campaign active - does it trigger a recalc of quest's available cache for a student?

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1180]
Available quests are cached.  That cache is updated (via post-save signal) whenever a quest, badge, or prereq object is saved.

However now that campaigns can affect the availability of quests, "Category" model may need to be added to the models that trigger a re-calc of the prereqs cache.

First test:

- [x] Log in as a student and view available quests.
- [x] As staff, make one of the campaigns inactive.  Should see some celery action in the docker logs if viewing them in terminal with `docker-compose logs -f` 
- [x] As student, refresh screen a few times, do those quests disappear for student?

If there is no celery action in the logs, and the quest doesn't disappear, it means the student's cache of available quests isn't being updated.

Once you've tested this, please report results and I can provide more info if we need to update cache.

**Comment by 9921622** [comment]
Log in as a student and view available quests.
![image](https://github.com/bytedeck/bytedeck/assets/39788517/2cf6a694-cdde-44ba-9f30-2c047e11c7cf)

As staff, make one of the campaigns inactive. Should see some celery action in the docker logs if viewing them in terminal with docker-compose logs -f
![image](https://github.com/bytedeck/bytedeck/assets/39788517/c6125f3c-8e49-41d1-a8ec-8124c3adb50c)
![image](https://github.com/bytedeck/bytedeck/assets/39788517/7bb2ea31-a955-4df9-a6bc-eecb71765214)

As student, refresh screen a few times, do those quests disappear for student?
![image](https://github.com/bytedeck/bytedeck/assets/39788517/73f3607b-0d9b-4a1f-b1b7-bc14c4417fc5)

**Comment by tylerecouture** [comment]
Boom. Thank you!  Been a while since we've been sub 200 issues!
