### ISSUE TITLE
Tests needed for PR #1198

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1204]
https://github.com/bytedeck/bytedeck/pull/1198

**Comment by tylerecouture** [comment]
@9921622  Is there a test that checks what is done it that PR? I.e. the XP for the tag includes quests completed and badges earned?

**Comment by 9921622** [comment]
this pr https://github.com/bytedeck/bytedeck/pull/1593 does check the formatting of quests. But ill work on a pr for badges

**Comment by tylerecouture** [comment]
This isn't about formatting, it's that the value is correct and includes quests AND badges with the tag

**Comment by 9921622** [comment]
got it. since the view uses ```get_badge_assertion_by_tags``` and ```get_quest_submission_by_tag``` ill add a new test case for them
