### ISSUE TITLE
Tag detail view shows duplicate ordinal for repeatable quests

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1210]
![image](https://user-images.githubusercontent.com/10604391/188282101-61325658-7f06-426c-b2c7-3714ca05eb58.png)

**Comment by yujinyuz** [comment]
This seems to have been fixed with other PRs after investigating

<img width="648" alt="image" src="https://github.com/bytedeck/bytedeck/assets/10972027/c932d080-5b69-48e7-8c70-a8ceb57c6320">

**Comment by tylerecouture** [comment]
@yujinyuz your screenshot shows the same bug?  The duplication of the ordinal (2)(2) instead of just (2).
