### ISSUE TITLE
Can't delete student course from edit form

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1215]
Should be a delete button and a confirmation page:

/courses/edit/1882/

![image](https://user-images.githubusercontent.com/10604391/188698638-eaeb6586-1c7b-4c8c-8340-71bfc34c8404.png)

**Comment by yujinyuz** [comment]
@tylerecouture 

Already has a delete button and delete view
https://github.com/bytedeck/bytedeck/blob/8cabba69a0d5e137e0c65a131384b20abd7770da/src/courses/views.py#L330

**Comment by tylerecouture** [comment]
Duplicate of #1238 which was fixed.
