### ISSUE TITLE
Break buttons on mobile

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1218]
Buttons should break in the middle to prevent this:

![Screenshot_20220908-212405.png](https://user-images.githubusercontent.com/10604391/189271726-2ade948a-3a43-4ec8-b5b2-76cb05037c5e.png)

**Comment by yujinyuz** [comment]
This looks like a tricky css bug to me. I'll put this on hold. Not quite good with css 😅

**Comment by tylerecouture** [comment]
No worries, I will remove you so you can focus on other issues!
