### ISSUE TITLE
tenant add form should not validate form if not unique

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1219]
Currently throws and error. Instead should invalidate form.

Internal Server Error: /admin/tenant/tenant/add/

IntegrityError at /admin/tenant/tenant/add/
duplicate key value violates unique constraint "tenant_tenant_name_69c42476_uniq"
DETAIL:  Key (name)=(pe10-12) already exists.

**Comment by yujinyuz** [comment]
@tylerecouture Can't reproduce this issue as it already invalidates the form..

<img width="997" alt="image" src="https://user-images.githubusercontent.com/10972027/205439948-0d03f219-039c-4dcd-abd0-bbc0653c240a.png">

**Comment by tylerecouture** [comment]
@yujinyuz I think the error only occurs if you use this form on the public tenant: /decks/new/

**Comment by yujinyuz** [comment]
Still can't reproduce this when using `/decks/new/`

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/10972027/206900998-aa91f3b6-48ca-418e-b0a8-4e16071212f0.png">
