### ISSUE TITLE
Fix typo in announcement emails 

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1220]
Maye

![Screenshot_20220912-101442.png](https://user-images.githubusercontent.com/10604391/189664138-fa4f01a8-d8af-40a4-8416-fb7a50262d27.png)

**Comment by ryuusama09** [comment]
Hi @tylerecouture , I would like to help ! .

**Comment by tylerecouture** [comment]
Go ahead!

**Comment by tylerecouture** [comment]
Let me know if you have any questions

**Comment by ryuusama09** [comment]
hi @tylerecouture , I cant exactly locate the source of this error .
I navigated into <bytedeck\src\notifications\templates> but it seemed that none of the templates were matching this format .Can you point out the file ?

**Comment by tylerecouture** [comment]
Try searching the entire repo.

**Comment by tylerecouture** [comment]
Closed by #1221
