### ISSUE TITLE
Assigning a badge to many students at a time

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1223]
It would be nice to be able to assign a badge to several people at a time by, perhaps, seeing a list of all students in the course with a checkbox beside the students so that we could simply check off the ones we want to have the badge.

**Comment by tylerecouture** [comment]
You can bulk assign a badge by hitting the green button with 3 heads icon, on the badge's page, or the badge's info popup.

You can then type in all the names you want to add (and it has a nice autocomplete which makes it quick)

However, there is no list and checkbox option which would be a nice enhancement!

**Comment by aluxenburg** [comment]
Yes. I have been doing it that way... but when I want to add 85 people to a badge it becomes very cumbersome.
