### ISSUE TITLE
Delete Decks

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1255]
It would be great to be able to clean up our tenant list by deleting old or test decks.

**Comment by tylerecouture** [comment]
This is currently disabled as a precaution and to prevent accidents.  We need to create proper protections and warnings for tenant deletion:

- [ ] When deleting a tenant in admin, need a popup verification, something like: "To confirm deletion of this tenant, enter the tenant's name: ___________"
- [ ] Only delete the tenant model object, leave the schema in the database (as a failsafe/backup
- [ ] When trying to create a new tenant, need to check if a schema exists on the db with that name, and then provides warning to delete the schema before creating a new tenant with that name.
