### ISSUE TITLE
Convert `Profile.grad_year` to optional `Profile.custom_profile_field`

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1273]
Grad year can be a bit confusing to adult learners (which we seem to be getting more of) and to elementary teachers and students.
Is it really necessary in profile or anywhere else?

**Comment by tylerecouture** [comment]
Agree. What if we turned it into a custom field that deck owners could call whatever they want, or leave blank to have it not appear at all?

A "Custom Profile Field" in their deck settings.

**Comment by aluxenburg** [comment]
That sounds good, Tylere.

**Comment by tylerecouture** [comment]
- [ ] Convert Profile.grad_year to optional Profile.custom_profile_field.  
- [ ] Migration should handle convertion of int field to new CharField with string data
- [ ] Include a new field in SiteConfig called `Custom Profile Field` and use that name as the label for the Profile.custom_profile_field on Profile forms.
