### ISSUE TITLE
Tags creation

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1282]
When creating tags from the admin access, if you don't use a hyphen instead of a space, it will not use the tag when "tagged" to a quest, it will create a new one with hyphens. So when I selected "Solve Problems" as a tag on a quest, it created a new one instead: "solve-problems". When I renamed the tags from admin, and added the hyphen to the name, it worked just fine. 
This could be very confusing for folks. We either need some help instruction on the Tag page or eliminate the recreation with hyphens.

**Comment by tylerecouture** [comment]
What's the reason for creating tags in Admin?

**Comment by aluxenburg** [comment]
Sorry... not in admin... the dropdown under admin has Tags where one can create tags in advance.

**Comment by tylerecouture** [comment]
Yep, I see the problem now. Thank you!  That form should work the same as when you create tags in a quest directly, and should have some help text too.

Problem form is at: 
`/tags/create/`
![image](https://user-images.githubusercontent.com/10604391/210878825-a5547a57-d129-499a-b169-59a6d8181e3a.png)



This single field/widget should work the same as the tag field/widget on the Quest Edit page, e.g.
`/quests/1/edit/`

![image](https://user-images.githubusercontent.com/10604391/210878718-172b3db0-9d0f-46c6-9fe8-dfed982f3a1c.png)

**Comment by bashu** [comment]
to @tylerecouture should I fix that too ?

**Comment by tylerecouture** [comment]
@bashu, please finish the Generic Foreign Key widget first before we look at anything else.
