### ISSUE TITLE
Request: View list of students who have been awarded a badge

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1285]
As badges are the most flexible and extensible means of organizing students, it would be great to be able to view all students who have been alloted a specific badge. Example: If I have 15 students in my Cohort 2 badge, I currently do not have a way of seeing the list of students with that badge; I need to visit each student's profile to see which badges have been awarded.

**Comment by tylerecouture** [comment]
Would be a very useful feature, especially as we start organizing students with badges, as you say.  

Every badge currently has a fairly empty page of it's own, it would make sense to list all the recipients there.  Maybe two tabs, currently enrolled students, and all time.  And users should cross-link to their profiles.

We probably also want to make the link to the badge's badge more obvious or intuitive (currently need to click the link icon in the title of the badge's popup)
