### ISSUE TITLE
Ability to change name of Announcements

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1294]
We now have the ability to change the name of tags and of blocks... which is great.
I would like to request the ability to change the name of announcements.
Why?
I don't feel that pages are useful as they are. They are easy to create, but not easy to make obviously accessible to students.
If we can change the name of announcements we can make it into course info or whatever fits our course. 
I didn't use announcements in my courses and it just sat there. 
I would have used it if I could change the name.

**Comment by tylerecouture** [comment]
This is part of the Ethos project, so I've consolidated the white-labelling into a single issue #1330
