### ISSUE TITLE
More robust wysiwyg editor???

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1295]
This is a wish.
I would love to see a more robust wysiwyg editor.
Why?
Well the one we have is quite limited.
If I want to do any "design" work, with items next to items in a web-style format, I need to use tables. This is fine, but I cannot make any formatting changes, like to borders... to make them transparent and such.
This is a wish.

**Comment by tylerecouture** [comment]
I think this would require an external tool (and paste in the html/css) or the ability to write CSS.  I don't see any path to implementing this within Bytedeck directly.  I'd also be interested in the use case.  For quest design, it seems undesirable to me.  For flatpages it might be useful to have multi-columns.

It is possible to add functionality to the existing widget we use through plugins.  We could commission the creation of specific plugins if funding was available for that.

**Comment by tylerecouture** [comment]
The new "Advanced" Editor completed in #1302  fully supports external tools now, so layouts and designs can be pasted in.
