### ISSUE TITLE
Google account sign on via OAuth2 (in addition to existing local account option).

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1296]
- Existing local account option remains
- If conflicting email addresses, method to "merge" local and OAuth account.

**Comment by tylerecouture** [comment]
- Existing local account option remains
- If conflicting email addresses, method to "merge" local and OAuth account.

**Comment by yujinyuz** [comment]
I can't seem to reproduce this locally..

Steps I did (done on an empty postgres data)

1. Checkout `git checkout a6436292`
2. Run `python src/manage.py initdb`
3. Checkout to latest `develop`
4. Ran `python src/manage.py migrate` for the siteconfig migrations
5. Verified that tables `socialaccount_socialapp` table exists via database GUI (pgAdmin or anything similar)
6. Accessed: http://localhost:8000/admin/socialaccount/socialapp/
7. Was able to create a social app


---

Did you have different steps when performing anything related to socialapp?

Also, could you verify that staging does not have the `socialaccount_socialapp` table?

**Comment by yujinyuz** [comment]
Steps to fix

```
python src/manage.py migrate socialaccount zero --fake
python src/manage.py migrate socialaccount
```
