### ISSUE TITLE
Implement two Summernote fields: 1. escaped/safe, and 2. unescaped

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1302]
Note that  I am going to use the `Quest.instructions` field for all examples, and the form at `quest_manager.forms.QuestForm`, although the problem exists everywhere we use this widget:
![image](https://user-images.githubusercontent.com/10604391/225453389-10879543-068e-4dea-9c74-82502b6aa5ba.png)

### Problems
Currently we use the `SummernoteInplaceWidget()` from [django-summernote ](https://github.com/summernote/django-summernote )for most of our `models.TextField` fields.

This provides us with a simple, expandable, configurable wysiwyg editor for our forms.

####  1. Undesired escaping/stripping behaviour: 
The current implementation has some major issues, demonstrated in the screen recording using `<script>alert("Hello")</script>`:

1. Enter the content: `<script>alert("Hello")</script>` into the summernote widget in the form
2. When saved, the text appears as expected.
3. However, when you edit the form, it executes the code!  You can see the alert pop up.
4. The text is also converted into code, so that it is no longer visible unless you switch to "Code View"
5. When switching OUT of "Code View", it appears to do some escaping and strips out the `<script>` tags

![Peek 2023-03-15 14-45](https://user-images.githubusercontent.com/10604391/225451196-d190f532-3afc-465b-a962-2aff0112041a.gif)

#### 2. iFrame version of the widget is bad:
A potential solution is to consider summernote's iFrame version of the widget, From [django-summernote](https://github.com/summernote/django-summernote) docs: 

> Warning: Please mind, that the widget does not provide any escaping. If you expose the widget to external users without taking care of this, it could potentially lead to an injection vulnerability. Therefore you can use the SummernoteTextFormField or SummernoteTextField, which escape all harmful tags through mozilla's package bleach:

However, in the past, SummernoteTextFormField or SummernoteTextField were only usable on the widget that used an iframe, which had other problems that made the widget unusable or undesirable, as shown here: (scroll bars and popup menus that are useless):
![image](https://user-images.githubusercontent.com/10604391/225454538-fad6c69e-7d19-454f-9b3c-9d6ccebe669a.png)

#### 1. Ability to choose escaping/stripping or not on a per-widget basis:

In our app, we need two versions of this widget: 

1. A "Safe" widget that escapes content entered in the text view (e.g. `<` are converted in the code to `&lt;`) and also strips script tags entered in the HTML/code view, 
2. An "Advanced" widget that still escapes content entered in the text view (e.g. `<` are converted in the code to `&lt;`) but does NOT escape or strip code that is entered into HTML/code view, including `<script>` tags.

This could be done by subclassing the existing widget, or modifying it from our own fork (it hasn't been updated in 2 years)

#### Consistent, predictable behaviour

1. The problems above need to be fixed or avoided.
2. Our versions of the widget need to be unit-tested against the above behaviour.

**Comment by bashu** [comment]
> An "Advanced" widget that still escapes content entered in the text view (e.g. < are converted in the code to &lt;) but does NOT escape or strip code that is entered into HTML/code view, including <script> tags.

Here is scenario, 
a) you enter `<script>something</script>` in richtext view, but then switch into codeview and above text should be escaped, correct? 

b) you switch back to richtext view and `<script>something</script>` should be there as text. 

c) you switch back to codeview enter `<script>another</script>` here and switch back to richtext view, the first `<script>something</script>` should remain as escaped html text, but `<script>another</script>` should be executed as inline script (but script element, should remain invisible in richtext view). 

d) finally you switch back to codeview and you can see both elements, first `<script>something</script>` as escaped html, and `<script>another</script>` as inline script block

Is that what you want, @tylerecouture ?

**Comment by tylerecouture** [comment]
Yes!

The execution of the script in "c" is not necessary, but I think it already does that by default?

More important is that the script runs when the field is rendered in a template/page with:

{{ quest.descrption }}

Though it might need the 'safe' filter to prevent escaping by Django.

**Comment by bashu** [comment]
> The execution of the script in "c)" is not necessary, but I think it already does that by default?

I don't get it, you want two widgets Safe and Advanced, I already made a Safe version. In advanced version you want to have ability to enter script tags "as-is" in a "codeview" of the widget and not be escaped, nor striped, but now you tell me it should be "unsafe", but "safe" in a same time, right? I don't get it, how it can be "unescaped", but "enescaped" in a same time, please clarify

**Comment by tylerecouture** [comment]
> > The execution of the script in "c)" is not necessary, but I think it already does that by default?
> 
> I don't get it, you want two widgets Safe and Advanced, I already made a Safe version. In advanced version you want to have ability to enter script tags "as-is" in a "codeview" of the widget and not be escaped, nor striped, but now you tell me it should be "unsafe", but "safe" in a same time, right? I don't get it, how it can be "unescaped", but "escaped" in a same time, please clarify

I'm sorry for the confusion!

I only ment that execution when switching between code view and rich text view is not necessary, but it isn't a problem either.  It's irrelevant.  The important execution is when we render the content outside of the form in a template, e.g with  `{{ quest.description }}`

Also, the `safe` django template filter tells django that the content doesn't need to be escaped.  e.g. if you try to put the field contents into a template with `{{ quest.description }}` it might escape everything and scripts wouldn't run.  Whereas if you put `{{ quest.description | safe }}` then we are telling django "this code is already safe, don't worry about it" so django renders it as-is without escaping it.

If my comments are confusing, you can ignore them!  Your description from a) to d) is good!  The only thing missing is that the script must be able to run when the content is rendered outside of the form view, when it's rendered with `{{ quest.description }}` or  `{{ quest.description | safe }}` in a template (i.e. in the detail view)

**Comment by bashu** [comment]
thank you @tylerecouture

**Comment by bashu** [comment]
@tylerecouture just to clarify, do you want to have both iframe and non-iframe variants of new widgets (like it was in original django_summernote package)? Then there will be four widgets: two "safe" (iframe and inplace (non-iframe) variant) and two "advanced" widgets. Also two admin classes, one for Advanced and one Safe widgets, "iframe" or "inplace" variants will be selected based on global summernote settings.

For me it's not a big deal to have four widgets ;-). Please let me know, I am pushing final commit.

**Comment by bashu** [comment]
to @tylerecouture there is not much extra work to make four widgets, I just want to be sure PR will match your expectations

**Comment by tylerecouture** [comment]
> @tylerecouture just to clarify, do you want to have both iframe and non-iframe variants of new widgets (like it was in original django_summernote package)?

I think we just need the non-iframe versions, but let me test them out to make sure they are working.

I would like to minimize customizations so the code is easier to maintain.

Thank you!

**Comment by bashu** [comment]
> I think we just need the non-iframe versions, but let me test them out to make sure they are working.

Too late, you have both now ;-D
