### ISSUE TITLE
Failing tests in bashu-GFK branch

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1323]
Here's the branch: https://github.com/bytedeck/bytedeck/tree/bashu-GFK-field

Here's the failing test: test_post_save_button__defaults and another the dev commented out with # TODO: broken

The tests only fail when there is a fresh database.  So it fails on github Actions, but not locally unless you remove the postgres_data volume before running tests.

**Comment by yujinyuz** [comment]
Just posting it here for reference. All ran on empty database

---
PASSED`quest_manager.tests.test_views.QuestPrereqsUpdate`

---

PASSD `quest_manager.tests`

**Comment by bashu** [comment]
to @yujinyuz did you test them separately, or have run all the tests at once?

**Comment by yujinyuz** [comment]
@bashu I tested them separately

**Comment by bashu** [comment]
@yujinyuz they fails only when you run all the tests

**Comment by yujinyuz** [comment]
@bashu You're right. I'm trying to isolate what causes the tests to fail that's why I was running them separately

**Comment by yujinyuz** [comment]
@bashu Could you rebase your branch to the latest develop?

@tylerecouture After investigating this and updating the branch to the latest develop, I couldn't reproduce this anymore..

You can take a look at it here and see that the builds are passing https://github.com/bytedeck/bytedeck/pull/1324

I even uncommented the other broken test

**Comment by tylerecouture** [comment]
@yujinyuz Now that it's rebased on develop, you can see it failing (one of them?) here:
https://github.com/bytedeck/bytedeck/pull/1284

**Comment by yujinyuz** [comment]
@tylerecouture That failing test is related to this one: https://github.com/bytedeck/bytedeck/pull/1326

**Comment by tylerecouture** [comment]
Yep, you're right.  Can you create a bug issue for this with as much detail as possible?  It has something to do with Date objects and timezone.  **This is midnight my local time,** which is the app's default timezone, so it has something to do with providing the wrong localized date I suspect...

I will rerun the tests on this in the morning and if it passes, will close this issue.

**Comment by tylerecouture** [comment]
**settings.py**
````
# I18N AND L10N ####################################################################

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Vancouver'
USE_I18N = True
USE_L10N = True
USE_TZ = True
````
