### ISSUE TITLE
Date field unexpected behaviour at midnight in app default TZ

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1327]
This bug can be observed in tests, if run at midnight in default TZ (settings.py: `TIME_ZONE = 'America/Vancouver'`)

See PR #1326.

I suspect one of these tests fails 1 hour before midnight to midnight, and the other fails from midnight to one hour after:

**QuestTestModel.test_active()**

```
        # create and test a quest that won't be available until one hour later in the same day
        baker.make(
            Quest, name="future-time-quest", date_available=timezone.localtime(),
            time_available=(timezone.localtime() + timezone.timedelta(hours=1)))
        self.assertEqual(Quest.objects.get(name="future-time-quest").active, False)
```

and

```
        # create and test a quest that's expired one hour ago
        baker.make(Quest, name="past-time-quest", time_expired=(timezone.localtime() - timezone.timedelta(hours=1)))
        self.assertEqual(Quest.objects.get(name="past-time-quest").active, False)
```

So...we need a test that specifically covers midnight for these two (freezetime?) and fails on existing code, and then a fix.These should be placed in their own test method.

**Comment by tylerecouture** [comment]
It's BACK!

**Comment by yujinyuz** [comment]
I think the proper way to fix this is to store everything in UTC (which is the timezone.now) and then display everything in the local timezone.

But I think this is going to be messed up because there are already data inside production in which we dont know what timezones they are stored in

**Comment by tylerecouture** [comment]
Actually, the test is good, the bug is in the code itself.  I fixed it once, but then refactored the code significantly and that reintroduced the bug...haha.

**Comment by tylerecouture** [comment]
@9921622 I fixed it once, here: https://github.com/bytedeck/bytedeck/commit/7757a22365f28b6d874a5777f77734225c27d076

Then it broke again a while later after refactoring code.

**Comment by 9921622** [comment]
no errors when built at 11:50
![image](https://github.com/bytedeck/bytedeck/assets/39788517/df0ec35e-ba18-463f-97e4-408d97a9a805)

im going to try again tonight

**Comment by tylerecouture** [comment]
Interesting.  Try again at 11pm tonight
