### ISSUE TITLE
Add indicators to "Advanced" Summernote widgets

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1334]
We need a visual indicator for "Advanced" summernote widgets:

- [x] Make the codeview icon red or yellow (or otherwise different)
- [x] Change the the hover-text to this: "Advanced Code View: scripts will run; with great power comes great responsibility!"

**Comment by bashu** [comment]
can not assign it to myself, but working on it

**Comment by tylerecouture** [comment]
Closed by 1338
