### ISSUE TITLE
Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1350]
We need to handle this error by providing user feedback instead of just an error page, since it's not clear to the user what the problem is.

This can be reproduced by editing a quest description too contain too much data (waaaay to much, so will need to paste in a LOT of text)

**Comment by bashu** [comment]
to @tylerecouture assign me

**Comment by bashu** [comment]
> This can be reproduced by editing a quest description too contain too much data (waaaay to much, so will need to paste in a LOT of text)

FYI, just set `DATA_UPLOAD_MAX_MEMORY_SIZE` to one byte to reproduce it
