### ISSUE TITLE
Custom deck css and js

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1365]
Allow deck owners to upload a custom css file and a custom js file.

- These should be two new fields in the SiteConfig model, and should only be editable by the deck owner (similar to the deck owner field itself)
- This should be in a collapsible, "Advanced" section of the form along with the deck owner field (similar to how the Quest form that has a collapsible Advanced section)
- There should be some simple check on the field that the files or of the correct type (js and css, file extensions at least)
- The CSS should be inserted LAST (i.e. highest priority) in the css stack in `templates/head_css.html`.  For an example of similar behaviour, see this code in the same file:

```{% if config.get_favicon_url %}
      <link rel="icon" href="{{ config.get_favicon_url }}">
{% else %}
```
- The JS file should be loaded, if it exists, at the bottom of templates/javascript.html
- A simple test that provides a (blank?) css file to the test tenant siteconfig and verifies it is included in the html returned from the a view
- A simple test that provides a (blank?) js file to the test tenant siteconfig and verifies it is included in the html returned from a view

**Comment by tylerecouture** [comment]
@bashu, see this bug reported by the organization that funded this feature:

One issue: Trying to upload a javascript file doesn’t seem to work – looks like the mime types don’t align.

![image](https://github.com/bytedeck/bytedeck/assets/10604391/eaa3b568-f50b-4446-982d-c0aba750074b)

Did some googling to see if it was something I did, but it looks like there are 3 common mime types for js files, though apparently it’s been fractured for a while:

- application/javascript (apparently supposed to be the standard now? I didn’t get this with the attached file so not sure)
- application/x-javascript (apparently an older standard?)
- text/javascript (when I put the JS file through https://mimetype.io/ it comes up with this).

**Comment by bashu** [comment]
to @tylerecouture next time please tell what web browser your client uses, thank you. And send "broken" file, just in case...

**Comment by bashu** [comment]
see https://github.com/bytedeck/bytedeck/pull/1385

**Comment by bashu** [comment]
for reference https://www.iana.org/assignments/media-types/media-types.xhtml

also from : https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.5

> Use of program names for the identification of encoding formats
        is not desirable and is discouraged for future encodings. Their
        use here is representative of historical practice, not good
        design. For compatibility with previous implementations of HTTP,
        applications SHOULD consider "x-gzip" and "x-compress" to be
        equivalent to "gzip" and "compress" respectively.

latest bugfix includes all three possible mimetypes for javascript files

**Comment by tylerecouture** [comment]
Fixed!
