### ISSUE TITLE
Pluralize bug

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1366]
![image](https://github.com/bytedeck/bytedeck/assets/10604391/a04a619f-bc49-4b2e-b0aa-fb0827831037)

Missing closing brace?

**Comment by punctuations** [comment]
I have no idea how this slipped through

**Comment by punctuations** [comment]
Oh this wasn't me, I did possessives not pluralizations, I can still make a fix though

**Comment by tylerecouture** [comment]
You're right! Apologies. Git Blame lays it on @Toranian 2 years ago

I can't believe no one has pointed this out in 2 years!
