### ISSUE TITLE
Creating maps with duplicate initial objects results in error

### ISSUE THREAD

**Issue by Dylan-RG-Patterson** [bytedeck/bytedeck#1370]
When creating a new map object through the create view, selecting a Quest, Rank or Badge as an initial object that is already an initial object for another map throws an error.
![image](https://github.com/bytedeck/bytedeck/assets/105619909/bfd4687c-5098-488d-bf06-985495af076f)
Results in this error:
![image](https://github.com/bytedeck/bytedeck/assets/105619909/5900df5d-a4e4-403f-9de2-58dc55a94d8c)

Exception Type: IntegrityError at /maps/generate/
Exception Value: duplicate key value violates unique constraint "djcytoscape_cytoscape_initial_content_type_id__6fc35a3b_uniq"
DETAIL:  Key (initial_content_type_id, initial_object_id)=(39, 1) already exists.

**Comment by Dylan-RG-Patterson** [comment]
@tylerecouture 
Here is the issue for the problem described in https://github.com/bytedeck/bytedeck/pull/1368. 
Needs the "bug" label, fairly certain I lack the permissions to add it myself at the moment.

**Comment by tylerecouture** [comment]
This needs our GFK select field to be filterable.

**Comment by bashu** [comment]
can confirm the bug, working on a fix
