### ISSUE TITLE
Campaign Default Sorting/Filtering

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1381]
Just diving into the campaign section of ByteDeck. I hadn't realized I could see all the quests that are in a campaign. Really useful! Now I need to clean house of old campaigns.

Could it be setup so that **active campaigns appear in a separate section** as inactive campaigns? There could be an active table at the top and an inactive table at the bottom? 

**Alternatively, a filter that could be selected to hide inactive campaigns**. For me, I would prefer the filter of hide inactive campaigns to be the default, but I might not be the average user. Maybe this is only an issue for ST/HS at the moment as we have a lot of

**Comment by fjbagley** [comment]
Maybe I should just be deleting campaigns?

**Comment by tylerecouture** [comment]
Haha, I would clean house and delete old stuff =)

**Comment by fjbagley** [comment]
Deleting them will remove the references in archived quests though. I could see a use case where a teacher stops using a software archives the quests and then wants to bring them back. They would need to recreate the campaign and then relink all of the quests to that campaign. 

Maybe add an archived check like in the quests?
