### ISSUE TITLE
Add Common Quest Info to Dropdown Admin Menu

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1384]
Doesn't seem to be there. Is it in a different location?

**Comment by tylerecouture** [comment]
It's in the Quests dropdown.  Should it be added to admin as well?

**Comment by fjbagley** [comment]
I didn't even see the quest drop downs until now. Obvious now you mentioned they are there! So many new features :). It would make sense to also go in the admin drop down as well. That is where many similar items go under the course setup.
