### ISSUE TITLE
Admin action on public tenant to send emails

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1386]
e.g. https://stackoverflow.com/questions/18619577/using-django-admin-actions-to-send-bulk-emails.

Create an Tenant model admin action (public tenant only) that will send emails to selected tenant "owners"

- owner emails taken from the "owner" user (see SiteConfig.owner) for each deck.
- Field for email title
- use Summernote Safe Widget to draft email body
- email sent via celery task

**Comment by bashu** [comment]
> public tenant

just to clarify, by "public tenant" do you mean tenant with schema name == "public" ? if so, there should be one single "public" tenant, correct?
