### ISSUE TITLE
/utilities/menuitem/ external non-relative urls always open in new tab, regardless of setting.

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1397]
If you set a non-relative link to NOT "open in a new tab" it will still open in a new tab.  The option works for relative urls such as `/courses/ranks/` but not for full urls `https://hackerspace.bytedeck.com/courses/ranks/

I believe there is some javascipt/jquery in the base template that add `target="_blank"` to any non relative links after a page loads.

![image](https://github.com/bytedeck/bytedeck/assets/10604391/b513c05e-3c93-4664-9643-a847ecaa0f9f)

**Comment by bashu** [comment]
to @tylerecouture assign me
