### ISSUE TITLE
Audio Stripped from Announcements

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1401]
I can preview an audio file in and announcement, but when I click update, the sound is removed. Can audio be allowed instead of stripped?

See the Art Challenge II - Horror - Results announcement for details.

**Comment by fjbagley** [comment]
![Audio](https://github.com/bytedeck/bytedeck/assets/37415548/46de1742-dd74-40fc-bef2-a7a31369fa1b)

**Comment by tylerecouture** [comment]
We can if we want the Announcements to allow all scripting.  Since they are only editable by staff members, this is probably ok.  We'd just need to switch the widget to SummernoteAdvancedWidget similar to that used in quests.

**Comment by tylerecouture** [comment]
Actually, Audio tags should work anyway.  Need to add Audio to the list of acceptable tags.
