### ISSUE TITLE
bootstrap-table bugs with muted / skipped submissions

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1403]
When a staff member skips a submission by hitting the SKIP button instead of the APPROVE button, it appears in the Approved (for staff) and Completed (for students) and are styled as muted / grayed out.

However, there are two issues:

1. In the student view (at least in light theme) there is no border for the muted panel when expanded
2. In the teacher's expanded view, their is a big blank gap for some reason, and the quick reply form doesn't appear.
![image](https://github.com/bytedeck/bytedeck/assets/10604391/10ec12ea-c735-44b3-bef3-6f226a2d42ef)

**Comment by Enprogames** [comment]
@tylerecouture 
The border problem should be a pretty easy fix. I originally intended for there to be no border around muted rows, as I thought it would give it a more "muted" look, but I can add a blue border. And in that case, should I also add a blue border around the quest row when it is expanded?

![image](https://github.com/bytedeck/bytedeck/assets/11304586/cf2cb50d-3e71-402c-910b-33c49c9e4768)


Regarding the gap and hidden quick reply menu issues, I seem to be unable to replicate the problem. I've tried on a few different revisions (namely before and after my changes to the quick reply forms in PR #1404 ), but I can't get the gap to show up. Could you give more details? What commit were you on? Do you still experience this on the latest commit?

![image](https://github.com/bytedeck/bytedeck/assets/11304586/8ec811b2-4b29-4415-955d-99cf3aaa1a4e)

**Comment by tylerecouture** [comment]
I think the gap was fixed when you fixed the reply from thing? It's gone for me too.

**Comment by tylerecouture** [comment]
You can just leave it with the default outline to reduce code.

**Comment by tylerecouture** [comment]
I noticed that the entire content is muted. Is it possible to just mute the heading section? The part you click to expand?

**Comment by Enprogames** [comment]
> I noticed that the entire content is muted. Is it possible to just mute the heading section? The part you click to expand?

Yeah for sure. I'll get that done.
