### ISSUE TITLE
Incorrect Sorting of Achievements in Profile

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1411]
I have sorted my achievements in a certain order in the badge page, but they show up incorrectly in the Profile page. See below:

![Incorrect Sorting](https://github.com/bytedeck/bytedeck/assets/37415548/0739b7bc-43a1-4a5c-96e8-9e225b600d2d)
![Correct sorting](https://github.com/bytedeck/bytedeck/assets/37415548/da3c0054-837a-4a59-9ef8-21b9008bf94a)

**Comment by tylerecouture** [comment]
That might have been a caching issue.  It looks correct to me. Try again in a bit.  I can't remember how long the query data is cached for.

![image](https://github.com/bytedeck/bytedeck/assets/10604391/1c8d7bb0-45e3-46b2-ae4e-8bd1bed92024)

**Comment by tylerecouture** [comment]
Can you provide the student user ID or link to profile?

**Comment by fjbagley** [comment]
https://studiotyee.bytedeck.com/profiles/148/

and

https://studiotyee.bytedeck.com/profiles/321/

**Comment by fjbagley** [comment]
Order in badges is correct, but order in student profiles is not correct.
