### ISSUE TITLE
Access to Badge Information for Instructors

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1415]
When an administrator clicks a badge, it would be great if the badge information page opened. There are currently only options to edit the badge or grant the badge. I had no idea there was the badge assertions information until now as I believe it currently is only accessible through the maps.

**Comment by tylerecouture** [comment]
You get there via the link icon in the title (of the badge pop up) Definitely needs a better more obvious way to access.

**Comment by tylerecouture** [comment]
Also, all that Badge assertion info below the badge details is brand new, added in a recent update.  It would make sense to me to have an obvious "View Details" button that matches all the other detail buttons/icons on the site.  I don't know why I put that stupid link there!

![image](https://github.com/bytedeck/bytedeck/assets/10604391/55ac5472-dc0f-4d20-b168-53fdd0c0732e)
