### ISSUE TITLE
Calendar Button does not Work on Additional Semester Excluded Dates

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1416]
Bug: In create a semester, the calendar does not pop up when clicking on the calendar icon for dates after the first excluded day.

**Comment by tylerecouture** [comment]
Can you screenshot this?

**Comment by tylerecouture** [comment]
I can't reproduce this either. Any more info on this?

![image](https://github.com/bytedeck/bytedeck/assets/10604391/94e78b37-79c1-4e04-95c6-01e60a7cf20d)

**Comment by fjbagley** [comment]
Here is what happens for me. See screenshots for details:

1. Clicking the calendar icon works for the first item but added items the calendar icon does not work.
2. Clicking the box does work,
3. After clicking create, I get a 500 error
4. The semester is there, but the excluded dates that I added are not.
5. The excluded dates do not appear in django either.

![Semester Create](https://github.com/bytedeck/bytedeck/assets/37415548/a8790016-c232-413d-8b1e-1b45924b98df)
![Semester Create 2](https://github.com/bytedeck/bytedeck/assets/37415548/432c33ae-60df-4dca-9d7d-a2565e8c4d55)
![Semester Create 3](https://github.com/bytedeck/bytedeck/assets/37415548/436b2866-0a40-46f9-b00f-427281f14e17)
![Semester Create 4](https://github.com/bytedeck/bytedeck/assets/37415548/4534abf2-0032-4645-bb3d-bc0e8445402a)

**Comment by tylerecouture** [comment]
Error report:
```
Exception Type: IntegrityError at /courses/semesters/26/edit/
Exception Value: null value in column "date_type_id" violates not-null constraint
DETAIL:  Failing row contains (248, 2023-10-02, null, 26, Truth and Reconciliation).
```

**Comment by tylerecouture** [comment]
Looks like same error as #1241

**Comment by bashu** [comment]
to @tylerecouture assign me

**Comment by bashu** [comment]
to @tylerecouture I can not fix what I can not reproduce, do you have any ideas how to reproduce it?

![calendar](https://github.com/bytedeck/bytedeck/assets/144783/783c13c2-8586-4cc8-9d17-636bebad172c)

**Comment by bashu** [comment]
to @tylerecouture yes I can reproduce it, working on fix
