### ISSUE TITLE
Custom css rejecting valid properties

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1428]
The CSS custom upload (via Admin > Site Configuration menu) is rejecting apparently valid values.

For example, this stylesheet will be rejected:

```
p, a {
   word-break: normal;
   overflow-wrap: anywhere;
}
```

despite both being valid styles:
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by tylerecouture** [comment]
@bashu can you take quick look at why valid css is being rejected by your custom CSS upload feature?  Thanks!

**Comment by bashu** [comment]
to @tylerecouture it looks like CSSParser doesn't fully support "CSS Text Module Level 3" 
```shell
python -m cssutils.scripts.cssparse -s 'a {overflow-wrap: anywhere;}'
WARNING	Property: Unknown Property name. [1:4: overflow-wrap]
b'a {\n    overflow-wrap: anywhere\n    }'
```

**Comment by bashu** [comment]
solutions 

a) disable properties validation 

b) fix it in cssutils 

c) create and support our own css profiles, see https://cssutils.readthedocs.io/en/latest/profiles.html

solution **a** is quickest and easiest

**Comment by tylerecouture** [comment]
@bashu thanks for the explanation.  In the future we may look into creating an additional profile, or just add a few of these newer properties with https://cssutils.readthedocs.io/en/latest/profiles.html#cssutils.profiles.Profiles.addProfile
