### ISSUE TITLE
Modular main sidebar menu

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1437]
Add an option that allows for a list of menu items that can be added or removed from the main menu on the left sidebar:
![image](https://github.com/bytedeck/bytedeck/assets/10604391/94ce7948-f323-48e4-a222-7e50d9ce3cf1)

This should be set up similar to the menu list under the hamburger menu, where you can "Edit this list"

![image](https://github.com/bytedeck/bytedeck/assets/10604391/467f9c33-a017-484d-b107-f19538d34e18)

Actually, we might even be able to use the same model, just add a field that indicates which menu the items are for and filter appropriately for the topbar menu vs sidebar menu

The main sidebar menu currently has several items, the rendering should not change, only which items are listed.

- [x] Covert left sidebar menu to use the MenuItem model
- [x] Add an "edit this menu" option at the bottom for staff users
- [x] Two items should be hardcoded and NOT part of the refactor: Quests and Badges.  These both have submenus and should remain as they are now.
- [x] Users and Quest Approvals (staff only) should also be always visible to staff, hardcoded, and remain as they currently are.
- [x] **Maps, Announcements, Profile, Portfolio** can all be converted to MenuItem model
- [x] Above 4 items should be included in a new deck, so they'll need to be created along with other model data in tenant/initialization.py
- [ ] Above 4 items should  NOT be deletable in the MenuItem list.  However they can be set to visible = False.
- [x] Additional items can be added by provided an icon, url, and label (see MenuItem model), and the left sidebar should render it as a menu item.
- [x] Items should order according to the sort order (but Quests and Badges hardcoded on top, and Students and Quest Approvals hard coded on the bottom, i.e. not part of MenuItem)

**Comment by yujinyuz** [comment]
Does the custom menu bar need some kind of `active` indicator? I see some custom logic being implemented specifically the `Profile` as it contains this code

https://github.com/bytedeck/bytedeck/blob/26ba4244d5fc970e47d05543870a1096d9195134/src/templates/sidebar.html#L97-L102

**Comment by tylerecouture** [comment]
Active highlights the menu item blue by looking at the url. You could probably do something generic to see if the current url match the button's url? If they match you're on that page and set it active for the styling.

**Comment by yujinyuz** [comment]
@tylerecouture yup I was actually thinking of the same thing.

It's just this one url that I added wherein it specifically has a condition to only add an `active` class if it doesn't have the `/list/` in the profiles

**Comment by tylerecouture** [comment]
Oh, that's because there are two profile buttons.  One to view your own profile (the code you posted) and the other one is the list view which would have /list/ in the url.
