### ISSUE TITLE
tenant list view should use deck owner name and email

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1438]
The owner name and email address fields on the tenant model should be deprecated.  The SiteConfig.owner user on each deck/tenant should be retrieved and displayed on the tenant list view (Full name and verified email addresses.

For now, the fields can remain on the tenant model, but should have "DEPRECATED" along with the field name in the `verbose_ name` on the field.

**Comment by bashu** [comment]
to @tylerecouture assign me

**Comment by tylerecouture** [comment]
This view: `/admin/tenant/tenant/`

**Comment by tylerecouture** [comment]
"do you want these custom columns to be searchable in admin list?"

Yes!  Thank you.
