### ISSUE TITLE
Discrepency between file upload helptext and file upload size limit

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1486]
Files should be restricted based on a property in their FileField, e.g.
![f75788cb-c27f-4be1-8656-61aa1d5e13a8](https://github.com/bytedeck/bytedeck/assets/10604391/7b21d6ed-01b5-4711-b7cb-9ed2818fc296)

However, the current middleware appears to apply globally regardless:
![a0654905-4822-4703-8324-0ea12aaaeba2](https://github.com/bytedeck/bytedeck/assets/10604391/a8785da3-925d-48ed-b1f8-e8ccc0777fae)

**Comment by bashu** [comment]
do you want me to fix it?

**Comment by tylerecouture** [comment]
@bashu this is functioning, but I notice it gives an error page instead of a clean message or form invalidation, etc, which was the whole point of your previous project.
![image](https://github.com/bytedeck/bytedeck/assets/10604391/9e2c1ce5-ecd7-446a-827d-b1514f50e0ea)

**Comment by bashu** [comment]
to @tylerecouture the form, which one?

**Comment by bashu** [comment]
I will fix that too
