### ISSUE TITLE
New deck workflow improvements

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1489]
on the public tenant: `/decks/new/`

- [x] Set the owner's username to firstname.lastname (instead of "owner")
- [x] Set the owner's password to firstname-deckname-lastname
- [x] FIX broken email verification link that is sent (it does not use the subdomain, so the link doesn't work.  e.g. bytedeck.com/accounts/confirm-email/.... instead of deckname.bytedeck.com/account/confirm-email/...
- [ ] Once the owner user has verified the email (need to hook into that somehow?) for the first time, send an email with instructions for how to log in with the username and password.

**Comment by tylerecouture** [comment]
@bashu everything is done here except the email sent doesn't include the login instructions.  I'm not worried about format, but I need the pw passed into the template at least?  How do I get it?

**Comment by tylerecouture** [comment]
@bashu 
I need the username and password in the template.  {{ user }} is all that currently is there, which may or may not be the username...

**Comment by bashu** [comment]
> I need the username and password in the template. {{ user }} is all that currently is there, which may or may not be the username...
```html+django
{{ user.username }} {# for username, or {{ user.first_name }}.{{ user.last_name }} #}

{{ user.first_name }}-{{ tenant.name }}-{{ user.last_name }} {# for password #}
```
