### ISSUE TITLE
Refactor periodic tasks creation

### ISSUE THREAD

**Issue by yujinyuz** [bytedeck/bytedeck#1510]
We currently have a function that creates periodic task for all tenants for sending out emails.

https://github.com/bytedeck/bytedeck/blob/06943bddc318dcf444c1a36b3fec7211dc56a8b4/src/notifications/apps.py#L12-L16

This is not a good approach since that function only gets run if we re-deploy an the application or by re-running the `manage.py runserver` command.

- [x] Convert any periodic task to use the dispatcher task pattern as recommended by `tenant-schemas-celery`: https://github.com/maciej-gol/tenant-schemas-celery#dispatcher-task-pattern
- [ ] Make sure to manually delete the tasks within any deployed instance in the database so that celery won't pick it up
- [x] Update django-celery-beat and tenant-schemas-celery if possible

**Comment by tylerecouture** [comment]
Thank you!
