### ISSUE TITLE
XP Chart doesn't update during non-class days

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1513]
If a student earns XP during a weekend or an excluded date, the chart doesn't include the XP until the next non-weekend/non-excluded date.

However, it should be included in the same way it's included in the mark calculations explanation.

This means that for chart data, each date should include not just <= current day, but < next day.  i.e. the DAY BEFORE the next valid date.  So friday would also include any XP earned over a weekend, for example.  This way the calculations and the chart will match (red arrows should match, and blue arrows should match)

![image](https://github.com/bytedeck/bytedeck/assets/10604391/f9af013a-75ec-4ce0-a12b-69bd1df9a87d)

**Comment by yujinyuz** [comment]
@tylerecouture 

I haven't worked on the charts feature before. Is there any easy way I could load this data into my local deck? Or is there a way I could generate this to easily reproduce this?

**Comment by tylerecouture** [comment]
@yujinyuz  Don't worry about this one =)
