### ISSUE TITLE
Bad HTML in Quest list Table row

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1514]
An extra quotation mark is being added.  This is from /quests/available page:

![image](https://github.com/bytedeck/bytedeck/assets/10604391/5bb8a5e4-a27c-4ae4-b9a0-403c4ede6028)

**Comment by Obikaviola** [comment]
Can I be assigned?

**Comment by tylerecouture** [comment]
@Obikaviola let me know if you need any assistance!
