### ISSUE TITLE
Tag detail button info

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1522]
Should say: "View details for this Tag" instead of "View page"
![image](https://github.com/bytedeck/bytedeck/assets/10604391/b3928631-c05c-4b1f-a739-345c76ebb5c4)

**Comment by sfazli96** [comment]
Hi! I am open to give this issue a try. If possible please assign me and I can give it a try.

**Comment by SoftwareGuyAshish** [comment]
I would like to resolve this issue. Please assign this to me

**Comment by sfazli96** [comment]
Ok, I opened a pull request u can check it out there.

**Comment by tylerecouture** [comment]
Thank you!
