### ISSUE TITLE
404 Error Portfolios of New Students

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1537]
All my new students are getting a 404 error when they click on the portfolio button. Returning students are not having this issue.

**Comment by tylerecouture** [comment]
Fixed in next update.  #1496

**Comment by tylerecouture** [comment]
@fjbagley this is in production now, can you verify it's working for you?

**Comment by fjbagley** [comment]
I'll get students to take a look tomorrow.

**Comment by fjbagley** [comment]
That works. Thanks!
