### ISSUE TITLE
Announcement emails still being send to users after a verified email is deleted on profile

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1551]
Reproduce:

1. Create a new user, turn on announcements by email, add an email address and verify.  Have them join a course.
2. As admin, publish an announcement.  the user above should receive, as expected.
3. As admin, edit the user and delete their email address in their profile.
4. Publish a new announcement.
5. The user STILL receives the new announcement email from the old verified email address, WHY?

Also:
6. As admin, edit the user and untick the "Active" at the very bottom.  Student should now appear in the inactive students list (/profiles/list/inactive/)
7. Publish a new announcement.
5. The user STILL receives the new announcement email despite being inactive, WHY? Is it because they are still registered in a course?  regardless inactive students should be excluded.

**Comment by yujinyuz** [comment]
@tylerecouture 

Not related to the bug reported here but just posting. 

Were there any recent changes in the editor we're using? I tried with multiple browsers and get the same result

<img width="1840" alt="Screenshot 2024-01-14 at 12 41 21" src="https://github.com/bytedeck/bytedeck/assets/10972027/09d450c5-ea85-4020-9095-c1eb8da65928">

**Comment by tylerecouture** [comment]
A min-height was added to the buttons, but haven't seen this.

**Comment by tylerecouture** [comment]
> For the inactive bug, it seems that the `CourseStudentManager.all_users_for_active_semester` query doesn't filter the `is_active` field.

This is a bug.
