### ISSUE TITLE
Account Inactive?

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1553]
I tried to log in with  Gmail account and got this?

https://testing.bytedeck.com/accounts/inactive/

![image](https://github.com/bytedeck/bytedeck/assets/10604391/9796778b-6808-48a6-b760-33e000e1351a)

Huh?

**Comment by yujinyuz** [comment]
Can you look into django admin and check what the value of `is_active` for that user is?

**Comment by tylerecouture** [comment]
Yep it is.  I guess this is expected then!  Except the page isn't using our template, it's unstyled.
