### ISSUE TITLE
Confirmation page before closing a semester.

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1563]
"Before any students were added, I accidentally hit the close button on a semester while adding excluded dates. (A nice feature would be an "Are you sure?" pop-up to prevent this.)"

Similar to the DeleteView almost all models have (try deleting a Badge or Quest or Course etc.) except it closes instead of Deletes.

**Comment by Happyashbunny** [comment]
Hey there I'd be interested in working out this issue, if you could direct me to the module/folder responsible

**Comment by tylerecouture** [comment]
Hi @Happyashbunny  Thanks for your interest! I think this one will require a development environment set up and running (see the README.md and CONTRIBUTING.md, unless you're a whiz with django =)

To "close" a semester, which runs some code and flips a boolean field on the model, you click a button on this template:
  `/src/courses/templates/courses/semester_list.html`

```
        <a class="btn btn-danger" href="{% url 'courses:end_active_semester' %}" role="button"
          title="Close this semester. WARNING!  Once a semester is closed, it can't be re-opened. This will permanently record all student XP for the semester. Which means changing or deleting quests, submissions, or badges will no longer affect their marks.  It will also archive all announcements, and delete any in-progress submissions.">
          <i class="fa fa-calendar-times-o"></i>
        </a>
```

The views for this model are in:   
  `/src/courses/views.py`


Here's the function-based-view that requires a confirmation page before running (similar to a Delete View)

```
non_public_only_view
@staff_member_required
def end_active_semester(request):
    sem = Semester.objects.complete_active_semester()
    semester_warnings = {
        Semester.CLOSED: 'Semester is already closed, no action taken.',
        Semester.QUEST_AWAITING_APPROVAL: "There are still quests awaiting approval. Can't close the Semester until they are approved or returned",
        Semester.STUDENTS_WITH_NEGATIVE_XP: "There are some students with negative XP. Can't close the Semester until it is fixed.",
        'success': f'Semester {sem} has been closed: student XP has been recorded and reset to 0, in-progress quests have been deleted, and \
        announcements have been archived.',
    }

    if sem not in (Semester.CLOSED, Semester.QUEST_AWAITING_APPROVAL,
                   Semester.STUDENTS_WITH_NEGATIVE_XP):
        sem.reset_students_xp_cached()
        Announcement.objects.archive_announcements()

    messages.warning(
        request,
        semester_warnings.get(sem, semester_warnings['success']))

    return redirect('courses:semester_list')
```

**Comment by Happyashbunny** [comment]
@tylerecouture thanks for elucidating on the problem. I am looking into it.

**Comment by Happyashbunny** [comment]
@tylerecouture I've made a PR id-ed #1568.
