### ISSUE TITLE
Ensure inactive users should not be included in the all_users_for_active_semester query

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1586]
Confirm that `CourseStudentManager.all_users_for_active_semester` query includes the is_active field.  This query should exclude users if `is_active` is False.

We also need a unit test on that query confirming users are excluded if is_active=False

**Comment by mimi030** [comment]
Hey there! I've reviewed the models and related tests for this issue, and it looks like the query and unit test may have already addressed the reported problem. Could you confirm if this issue has been resolved and closed? Let me know if there's anything else needed.

Also, for the unit test, would it be possible to add a line to explicitly verify that users are excluded if is_active=False? This would enhance the test coverage. Thanks for your efforts on this!

```
class CourseStudentManagerTest(TenantTestCase):
  """ Existing test code """
  
  def test_all_users_for_active_semester(self):
    """ Existing test code """
    self.assertNotIn(self.student, CourseStudent.objects.all_users_for_active_semester(students_only=True))
```

**Comment by tylerecouture** [comment]
Thanks for verifying!
