### ISSUE TITLE
Limit voting to once per suggestion

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#159]
Some students have noticed they can vote multiple times on the same suggestion.  One student received 8 democrat badges (40XP) through this trick!  Would we be able to limit voting to once per suggestion?

**Comment by tylerecouture** [comment]
The current voting system is designed so that they get one vote per day (on anything).   I.e. students who vote once per day for the entire semester would vote about 80-85 times, so ya, about 40 XP.
Is that broken?  Or do you only want students to be able to vote once for each topic ever?

**Comment by fjbagley** [comment]
Ah, got it.  I was thinking that a student could get one vote per topic, but perhaps I just need to promote students putting up suggestions so there is more to vote on.

**Comment by fjbagley** [comment]
So it is working as intended.  The issue is my implementation :(

**Comment by tylerecouture** [comment]
Suggestions app removed.
