### ISSUE TITLE
Quest Not Coming Available

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1714]
After completing a quest and having it approved, some students do not have the subsequent quest available to them in their available quest tab. Digital Photography 1.2 to Digital Photography 1.3 (see screenshots)

![1](https://github.com/user-attachments/assets/03db504d-01c5-4fb6-8d9a-8fcd5054aa30)

![2](https://github.com/user-attachments/assets/945837c9-6bb6-45c2-beb6-e3f852046e51)

![3](https://github.com/user-attachments/assets/0a3d724c-ce08-4fb7-a9e6-3447eb0e1118)

They can access and complete the quest through the map and complete it that way.

The same thing it occurring for The Playground deck, but it appears to be consistent. User is having issues between AutoCAD basics 1. and AutoCAD basics 2.

**Comment by fjbagley** [comment]
@tylerecouture This seems to be happening for most quests now. Students are needing to go to the map most of the time to find the quests they need to keep track of. I'm going to do some research with the students now to see if I can find any patterns.

**Comment by fjbagley** [comment]
@tylerecouture Every quest submitted since about 2 weeks ago had not allowed the subsequent quests to be available in the quests tab. This lines up with when I submitted the first issue. 

I don't see any updates on the code since September 4th and available quests did work for the first 2-3 weeks of class, so maybe an issue on the server? 

This could be related to #1716

**Comment by tylerecouture** [comment]
@yujinyuz this is the issue I messaged you about, can you please take a look?

**Comment by tylerecouture** [comment]
@fjbagley can you add step by step instructions to replicate this?

**Comment by tylerecouture** [comment]
@fjbagley I'm hoping this is fixed now, can you confirm?  If anyone still has an issue, it should resolve with the next quest or XP they earn... I'm hoping...

**Comment by fjbagley** [comment]
Works now. Thanks!
