### ISSUE TITLE
Escalating Chillax line priveleges option

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#203]
Student suggestion:
> You could have two teirs of chillax, one at a B (can play web-games/ watch YouTube)and another at either 86 or 90%(console games/excused from class(maybe, don't really think that's the best idea but would likely have people striving for a better mark))

**Comment by fjbagley** [comment]
ST has limited chilax only to Friday afternoons for anyone above C+. Perhaps I have been too tight on this! Maybe B tier is chilax on Thursday/Friday and A tier is chilax any day. I like a C+ tier as well as B can be out of reach for some students.

**Comment by tylerecouture** [comment]
Currently it is customizable to mark only, you think we should add Day of Week too?  i.e. Day(s) + Mark would give a lot of flexibility to teachers.  What do you call yours?

**Comment by fjbagley** [comment]
Days of the week, times and levels would be the ultimate! A good job for
the developer :)

**Comment by fjbagley** [comment]
My one afternoon a week is called Fun Friday, but I will change it next
term. Maybe 3 afternoons a week.

**Comment by tylerecouture** [comment]
This was completed a while ago with the Mark Ranges model.
