### ISSUE TITLE
Map doesn't appear until going in and out of the maps fullscreen mode

### ISSUE THREAD

**Issue by aidenmitchell** [bytedeck/bytedeck#242]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30846409/66594807-adf4f880-eb4e-11e9-9623-26cc2591914e.gif)

**Comment by ilovecats516** [comment]
Update: The console reports this:
404 not found: /static/djcytoscape/js/cola.v3.min.js.map

**Comment by tylerecouture** [comment]
Ah... did you select cola as a layout option in the map settings?

**Comment by tylerecouture** [comment]
The only layout option installed by default is dagre

**Comment by tylerecouture** [comment]
Map layouts have been refactored. This shouldn't be a problem anymore.
