### ISSUE TITLE
Can't get to public portfolios and profiles

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#274]
"I already sent in a complaint about where if i click on someone's username it redirects me to my quests even if they have a public portfolio." (Kim)

**Comment by yujinyuz** [comment]
What part of the page did they click someone's username?

I tried:

1. Logging in as a student
2. Students Tab
3. Clicked 'All' filter
4. I can click **View** button under the portfolio column (given that the other student has a public portfolio)

**Comment by tylerecouture** [comment]
What happens if you click their username? Is it a link?

**Comment by yujinyuz** [comment]
Nope. Only the **View** button has a link. I might be looking into a different page
 
<img width="1305" alt="Screen Shot 2020-03-29 at 1 34 30 PM" src="https://user-images.githubusercontent.com/10972027/77841635-164d9a00-71c2-11ea-94ee-8d701c8de293.png">

**Comment by tylerecouture** [comment]
Gonna remove public portfolios
