### ISSUE TITLE
Speed up the all students page

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#336]
It's too slow to load!
/profiles/list/current/

**Comment by yujinyuz** [comment]
Can I request a dump or fixtures so I could populate my database and see what's causing the page to be slow?

**Comment by tylerecouture** [comment]
Yes.  I'll need to rebuild the fixture though because the new multi-tenancy made it more complicated.  

In the mean time, check out the django-debug-toolbar.  I suspect that it is doing way too many queries per student in the list, and the data generated in the view is probably very inefiicient, maybe some list operation that should be queryset operations?  is select_related needed?

**Comment by tylerecouture** [comment]
I haven't had a chance to do this, but the page is slow even on a demo site with only a few users in the list.

There is no way there should be 55 queries running for only 2 users!  The queries themselves are fast, it's accessing them through the template that slows everything down.  Plus imagine listing 200+ students!
![image](https://user-images.githubusercontent.com/10604391/80242568-6598b600-861a-11ea-966f-d2bcf4770166.png)

**Comment by tylerecouture** [comment]
Suggestion:

Add a temporary data migration to fill up the database (create new users in a loop, try 500 users?  Even though they aren't in a course, if you click "all", you'll be able to see them:

**Comment by yujinyuz** [comment]
@tylerecouture won't this cause tests to load? And also newly created tenants would have some random users

**Comment by tylerecouture** [comment]
I mean just create it, run migrate-schemas, and delete it (don't commit) to easily fill your tenants with student users. 

There nothing special about them, as long as the save signal is caught by the profile app to create the profile along with the user.
