### ISSUE TITLE
Clicking View on Site from Django Admin Leads to missing studiotyee prefix

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#384]
When I click the view on site button in django admin, the link leads me to https://bytedeck.com/quests/45/ instead of https://studiotyee.bytedeck.com/quests/45/

**Comment by scssconsulting** [comment]
@tylerecouture Can you create superadmin user for me, to investigate further?

**Comment by tylerecouture** [comment]
@scssconsulting don't worry about this one. Not really important and I can figure it out later.
