### ISSUE TITLE
django-tenant-schemas vs django-tenants?

### ISSUE THREAD

**Issue by yujinyuz** [bytedeck/bytedeck#405]
django-tenants seems to be more actively maintained compared to django-tenant-schemas.

Plus, django-tenants is a fork of django-tenant-schemas, looking at their documentation credits, it says:

> I would like to thank the original author of this project Bernardo Pires Carneiro under the name django-tenant-schemas. I forked this project as I wanted to add enhancements to make it work better with Django 1.8
If you are using Django 1.7 or below please use his project.

Should we consider using `django-tenants` instead?

**Comment by scssconsulting** [comment]
django-tenant-schemas is still an active project. It has more stars than django-tenants. django-tenant-schemas supports django 2.0+ as well. I wouldn't suggest jumping to django-tenants unless you have any specific reason. What are the features that you can't find in django-tenant-schemas but on django-tenant?

**Comment by yujinyuz** [comment]
I didn't see anything special in django-tenants. It was just that django-tenant-schemas' last commit was November.

Anyway, can close this since

**Comment by tylerecouture** [comment]
https://github.com/tomturner/django-tenants/issues/372

**Comment by tylerecouture** [comment]
Closed by #906
