### ISSUE TITLE
Error importing quests (techhub)

### ISSUE THREAD

**Issue by mizzgoldberg** [bytedeck/bytedeck#407]
![Screenshot from 2020-04-09 22-08-36](https://user-images.githubusercontent.com/55294487/78964625-aedff600-7aaf-11ea-9092-12f812818771.png)

**Comment by tylerecouture** [comment]
Figure out how to increase the file size limit for django-import-export.  Currently seems to bail somewhere between 200 and 400 kb.  Set limit to...4MB?  Also, give a more informative error message...

**Comment by tylerecouture** [comment]
Looks like this is usually related to embeded data uri images

**Comment by tylerecouture** [comment]
The bug that caused this (runaway whitespace) has been fixed.
