### ISSUE TITLE
Use pre-commit hooks

### ISSUE THREAD

**Issue by yujinyuz** [bytedeck/bytedeck#444]
While taking a look at flake8's source code, they are using pre-commits to lint their code. 

https://github.com/pycqa/flake8/blob/master/.pre-commit-config.yaml

Just nice to have since it makes code cleaner and more consistent

**Comment by tylerecouture** [comment]
I'm not sure I understand this.  What do we need to add?

**Comment by yujinyuz** [comment]
https://pre-commit.com/

Every time someone executes git commit or git commit -m "Fix bug"

It runs a set of commands listed in the pre-commit config file

e.g. This config runs autopep8
```
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
```

**Comment by tylerecouture** [comment]
Ahhh, I see, for those who forget to run flake8 before committing?

**Comment by yujinyuz** [comment]
Yes!

**Comment by tylerecouture** [comment]
added by @9921622
