### ISSUE TITLE
siteconfig error when access public tenant

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#508]
When you access the public tenant this error is thrown by the db container:

```
db             | ERROR:  relation "siteconfig_siteconfig" does not exist at character 680
db             | STATEMENT:  SELECT "siteconfig_siteconfig"."id"....FROM "siteconfig_siteconfig"
```

Guess at problem:
when you go to localhost:8000 , the template is trying to access siteconfig before it redirects, but SiteConfig is a tenant app so doesn't exist on the public tenant.

Not sure how to fix?

**Comment by yujinyuz** [comment]
I don't see any problems moving it to `SHARED_APPS` 😸

**Comment by yujinyuz** [comment]
or we could also use this https://django-tenant-schemas.readthedocs.io/en/latest/install.html?#PUBLIC_SCHEMA_URLCONF

**Comment by tylerecouture** [comment]
PUBLIC_SCHEMA_URLCONF is exactly what we want!  Want to take a stab at it? I don't know where this would go. Tenants app?  New 'public' app?

**Comment by yujinyuz** [comment]
Sure! What should we display with the new view btw?

Also, I've found out that there isn't much difference between putting an app in the TENANT_APPS or the SHARED_APPS. If we want to make the main app work like the tenant apps, SHARED_APPS and TENANT_APPS could basically be the same list of applications.

**Comment by tylerecouture** [comment]
As far as I understand, if an app is in SHARED_APPS, then it will appear in the public tenant, and the public tenant can add objects.  Thos objects can then be used in all other tenants.  I'm not sure if they are included in the default queryset of the model, or if you have to do something special, but tenants have access to the public tenant's objects (but... I'm not positive about any of that!.  For our purposes, the public tenant doesn't need to have anything.  Eventually it'll just be a landing page with an onboarding form/process for a subscriber to create their own tenant.

**Comment by tylerecouture** [comment]
Still happening on admin site.... why?

**Comment by tylerecouture** [comment]
Still a problem, not sure why?

This error occurs when you access the public tenant admin: `http://localhost:8000/admin/`

```
db_1           | ERROR:  relation "siteconfig_siteconfig" does not exist at character 733
db_1           | STATEMENT:  SELECT "siteconfig_siteconfig"."id", "siteconfig_siteconfig"."site_name", "siteconfig_siteconfig"."site_name_short", "siteconfig_siteconfig"."access_code", "siteconfig_siteconfig"."banner_image", ...etc

```

But why is it even trying to get a SiteConfig object?

If look at `hackerspace_online.context_processors.config` it checks the tenant first, so there is somewhere else in the code that is trying to get the SiteConfig object even on the public tenant.

**Comment by yujinyuz** [comment]
Let me investigate this further

**Comment by yujinyuz** [comment]
Did this only occur after my latest PR?

**Comment by tylerecouture** [comment]
Nope, has always occured since SiteConfig model was introduced
