### ISSUE TITLE
Question/Answer in Quest Submission

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#550]
Admin could create a list of questions with answers. 
E.g. 
Question 1:
What is the best game ever created?
Answer 1:
Tetris

Student view would have a space to answer just below the question. 
This would make comparison of student answers to actual answer very easy.
Future uses could be quest could ask a random selection of the questions say 3 of the 5 questions. This would avoid students just copying answers from other students.

**Comment by fjbagley** [comment]
When the time allows, and I am sure it won't be anytime soon, Studio Tyee would like to sponsor this feature request.

**Comment by tylerecouture** [comment]
Re-posted in #1304
