### ISSUE TITLE
Popup of Badge after Earning

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#551]
Badges should be celebrated more. After a student earns a badge, a window should popup saying congratulations you earned x badge along with the details of that badge and how many bonus XP they earned with the badge. 

This would make badges a more powerful reinforcer and create more of an interest in earning badges. 

Khan Academy approaches the earning of badges in this way. A victory sound is also played when a badge is earnt.

**Comment by tylerecouture** [comment]
@9921622 you have some freedom to come up with something cool here.  Do you want this issue?

**Comment by 9921622** [comment]
@tylerecouture sure!
