### ISSUE TITLE
Connecting Learning Outcomes to Quests

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#552]
In meeting discussing a variety of LMSs at Carihi. The benefits of Canvas over Moodle were shared, teachers expressed that connecting learning outcomes to what is being learnt was very beneficial. 

Perhaps learning outcomes could be tied to quests?

**Comment by fjbagley** [comment]
This could lead into other ways of getting grades. Students earn XP, but a course might be setup where they need to earn a certain number of XP from each section. Science 10 might have chemistry, biology and physics sections.

**Comment by tylerecouture** [comment]
For the first part, what does this look like? A learning outcomes section in each quest?  Or is there a list of learning outcomes in the course the teacher creates, and then quests link to one or more of those Learning Outcomes?  Can you snag a screenshot of what how Canvas handles it?

**Comment by fjbagley** [comment]
I haven't used Canvas myself, but both Thomas and Matt really liked the feature. I would think there is a list of learning outcomes in the course and the quest links to those outcomes. I will see if I can find a screenshot or ask one of the aforementioned teachers to do so.

**Comment by fjbagley** [comment]
Here is a great overview including a video: [https://documentation.its.umich.edu/node/724#:~:text=What%20are%20Learning%20Outcomes%20in,development%20as%20they%20complete%20activities.&text=This%20opens%20in%20a%20new%20window.](url)

**Comment by tylerecouture** [comment]
Great video, thanks.  That's a cool feature.

**Comment by tylerecouture** [comment]
Consolidating these issues into one, since it is duplicated several times.

**Comment by tylerecouture** [comment]
Consolidating into #960
