### ISSUE TITLE
Basic prereqs not in order

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#556]
In the main quest form for create/update/copy the quests aren't in alphabetical order.  Use Select2!
Same with Badges

 New quest/badge prerequisite field under Basic Prerequisites form section

**Comment by yujinyuz** [comment]
I tried creating a Quest titled `Zelda's Legend` and it was listed at the bottom of the selection. I also created `Adventure Quest` and it was added at the top.

Can I see an example from yours?

<img width="879" alt="Screen Shot 2020-08-05 at 10 39 29 AM" src="https://user-images.githubusercontent.com/10972027/89365780-f302a080-d707-11ea-9008-646fd844658d.png">

**Comment by tylerecouture** [comment]
I think the Quest model is sorted by sort_order and then alphabetical. So
if you have given a quest a different sort_order value, it won't show up in
alpha order, which in this context is confusing.

However, now that I think about it, there's another issue to convert all
these field to use Select2 widgets, which wouldmake this issue irrelevant
...

**Comment by tylerecouture** [comment]
Maybe its an uppercase lowercase thing?!
![image](https://user-images.githubusercontent.com/10604391/89452505-9bb5fd80-d712-11ea-8f69-3bcdec07be8f.png)

**Comment by tylerecouture** [comment]
Problem is sort order... need to only use sort order on Quest page... or resort items for this widget, which should be easy.

Example: Woozy here has a high sort order value and shows up on top out of alpha order
![image](https://user-images.githubusercontent.com/10604391/149639753-f4d40f08-dcdd-4847-83bc-bf88b0bdb058.png)
