### ISSUE TITLE
Unable to export student data to csv in Edge

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#564]
Got the following error message when exporting student information from students view to csv in edge. It worked in Chrome. ![image](https://user-images.githubusercontent.com/37415548/85462862-d39a2480-b55a-11ea-9f7b-1874c490d279.png)

**Comment by tylerecouture** [comment]
Can you let me know what version of Edge you are using? Thanks!

**Comment by fjbagley** [comment]
I tried it on Edge on my Dell and it worked fine. I believe I was using the
lab computer when it didn't work. Perhaps an issue with just that machine
or just a restart was required?

**Comment by tylerecouture** [comment]
Ok, I'm going to close this one for now.  Just reopen it if it happens again with any additional details you can provide. THanks!
