### ISSUE TITLE
assets created via tenant initialization not found

### ISSUE THREAD

**Issue by yujinyuz** [bytedeck/bytedeck#589]
e.g. `icons/myAvatar.png`, `icons/cc.large.png`

<img width="849" alt="Screen Shot 2020-08-06 at 7 32 54 AM" src="https://user-images.githubusercontent.com/10972027/89474048-133d6880-d7b7-11ea-9861-4c70a1fd00ad.png">

perhaps it can be solved via #584 by downloading the images online? or maybe we should include the images in the source?

**Comment by tylerecouture** [comment]
fixed in #1109
