### ISSUE TITLE
Change Log not Accessible

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#650]
The link to the Change Log (Menu Top Right -> ChangeLog) takes to the old Hackerspace Changelog.  The Admin->Changelog has the correct link, but this is only accessible if you have access to the bytedeck repository. Can this be made publicly viewable?

**Comment by tylerecouture** [comment]
Changelog in top right is yours to customize, you can remove, set to the bytedeck changelog (though students prolly won't care about that) or create your own changlelog for your deck for students to see.

Admin > Changelog is now accessbile again by everyone.
