### ISSUE TITLE
Handle images in notifications more gracefully

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#755]
When there is a reply that is only an image or includes an image, get something like this which is kinda ugly:

![image](https://user-images.githubusercontent.com/10604391/101295843-e3d65100-37d4-11eb-9769-e57fcc9967d1.png)

Try approving a quest with only an embedded image to reproduce.

**Comment by tylerecouture** [comment]
Strip HTML for notifications with 
`from django.utils.html import strip_tags`

**Comment by 9921622** [comment]
gonna try to fix this one

**Comment by tylerecouture** [comment]
Please focus on issues I've already assigned to you first.
