### ISSUE TITLE
Badge importing error

### ISSUE THREAD

**Issue by mizzgoldberg** [bytedeck/bytedeck#794]
Trying to import 3 badges (talents) from Hackerspace to new Wolfmedia site. Error:
[badge_import.pdf](https://github.com/bytedeck/bytedeck/files/5861303/badge_import.pdf)

**Comment by 9921622** [comment]
@tylerecouture has the badge export been removed?
![image](https://github.com/bytedeck/bytedeck/assets/39788517/b696efc3-4320-460d-a53b-43293191f293)
