### ISSUE TITLE
Missing Comments and Submissions when Resubmitted

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#828]
A student has submitted a quest. I returned it, when he resubmitted, his original and my comments were deleted. In notifications, I can see that I had returned the item, but we were unable to locate it in their previous submissions in site administration. See attached:

![image](https://user-images.githubusercontent.com/37415548/114438971-496c8c80-9b7d-11eb-824a-548d9f6e4555.png)

This is the submission: [https://studiotyee.bytedeck.com/quests/submission/20811/](
).

Other students have had things returned and the returns show up.

On a completely unrelated note, great attachment popup!

**Comment by tylerecouture** [comment]
@fjbagley has this happened to you since? I'm wondering if this was a temporary issues from update struggles I had back then

**Comment by fjbagley** [comment]
I haven't had a student mention it since. I will ask the class tomorrow to see if it has happened recently

**Comment by tylerecouture** [comment]
@fjbagley any updates on this or can I close it?
