### ISSUE TITLE
Site breaks if there is no 0XP rank.

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#875]
Clicked on my profile, received a server error.
Tried a few times.

**Comment by aluxenburg** [comment]
Tried again on a different browser with my student account... .same result.

**Comment by tylerecouture** [comment]
```
Internal Server Error: /profiles/6/

AttributeError at /profiles/6/
'NoneType' object has no attribute 'xp'

...

File "/app/src/profile_manager/models.py" in xp_to_next_rank
  344.         return self.next_rank().xp - self.rank().xp

```

**Comment by tylerecouture** [comment]
@aluxenburg can you let me know what you were doing when this happened?  It looks like a problem with ranks, but I'm not positive.

**Comment by tylerecouture** [comment]
The app needs to handle cases where no rank is available at the current XP value.

rank() method on profile needs to handle when no rank is available:

```
    def rank(self):
        return Rank.objects.get_rank(self.xp_cached)
```

**Comment by aluxenburg** [comment]
Aha.
Broke it again.

**Comment by aluxenburg** [comment]
Thanks , Tylere.
Do you wish to have me start adding to documentation?
Leave that to you?
Avi

**Comment by tylerecouture** [comment]
Add away! That would be awesome!

**Comment by tylerecouture** [comment]
I'm going to leave the issue open because it's still a bug that needs to be permanently fix.

**Comment by tylerecouture** [comment]
todo:  If there is no rank at the given XP, then the rank provided should be "None" and use a default icon, perhaps fa-stop or fa-circle
