### ISSUE TITLE
Unable to delete certain users

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#876]
I am trying to delete two students who started the course, but transferred out. After getting to the confirmation screen that lists all the items that will be deleted, I click "Yes, I'm Sure" and get a 500 error. The users in particular are Christopher and Dragonborn. I was able to delete a test account that I created.

**Comment by tylerecouture** [comment]
This appears to be an issue with the deletion cascade, specifically with the "Document" model.

First guess: Deleting a user causes all their comments to be deleted, but that causes problems with any documents connected to that comment

```
IntegrityError at /admin/auth/user/
null value in column "comment_id" violates not-null constraint
DETAIL:  Failing row contains (11700, documents/2021/11/19/Screenshot_2021-11-19_095618.png, null).
...

**Comment by tylerecouture** [comment]
@fjbagley can you try deleting those users again? I removed the offending Documents (uploaded attachments) and I'm curious if that fixes the problem.
