### ISSUE TITLE
Robust Email Notifications (feature request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#883]
It would be wonderful to have a choice (students and teachers) to receive email notifications of quest activity (returns, acceptances, comments...).

**Comment by tylerecouture** [comment]
This feature was already partially implemented, in that students and teachers could get a daily summary email of stuff.

Cant remember why i turned that option off but if it's still in the code It'll be easy to add back!

Would you also want the option of instant email notifications, or are you just looking for a daily summary?

**Comment by aluxenburg** [comment]
If instant notification is not a problem… then yes, I would really like
that as an option.

**Comment by aluxenburg** [comment]
A daily summary would be fine... no need to make more work.

**Comment by tylerecouture** [comment]
Closed with https://github.com/bytedeck/bytedeck/commit/1fa717b726a31a47b39bf6a1ff78542ec6b04417

**Comment by tylerecouture** [comment]
Not working.
