### ISSUE TITLE
Function no longer works after update.

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#888]
I made a slight tweak to this quest: [https://studiotyee.bytedeck.com/quests/1411/](https://studiotyee.bytedeck.com/quests/1411/) and the function that calculates hours at the bottom of the quest details no longer works. Has the use of functions been removed?

**Comment by tylerecouture** [comment]
Not recently. It was probably a security fix that was made a long time ago, and editing the quest stripped it out.

Maybe you could put the code in a jsfiddle and link to that (you might even be able to embed it as an iframe, not sure)? Or if you think it's important, we could look into a feature that only allows JS for staff.

**Comment by tylerecouture** [comment]
You could also try putting it in a custom flatpage, js might still work there?

**Comment by fjbagley** [comment]
It is probably unnecessary. At the time I just wanted to see if I could do
it. I doubt it would get much (any?) use for users. Thanks for the
suggestions on workarounds.

**Comment by fjbagley** [comment]
It looks like jsfiddle is embeded through a acript and not an iframe. As it is a script, it gets stripped out from the quest.

**Comment by tylerecouture** [comment]
I'm going to close this.  It's not worth the security headache to allow javascript within quests at this point.
