### ISSUE TITLE
Whitespace and Imports

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#889]
Looks like there are a few new whitespace issues like #771

I've left them as is on your end so you can check them out.

[Godot Platformer 6](https://hackerspace.bytedeck.com/quests/1906/)
[Godot Platformer 8](https://hackerspace.bytedeck.com/quests/1909/)

**Comment by fjbagley** [comment]
After editing the CSV file to import into studio tyee, I noticed the white space appears only when a break element appears inside a h3 element. It was always <h3>heading here <br> whitespace </h3>

**Comment by tylerecouture** [comment]
Thank you! That info is super helpful.

Note: Temporarily Deactivate HTMTL formatting until this is fixed.

Potential fix (better regex/soup?): https://stackoverflow.com/questions/55962146/remove-line-breaks-and-spaces-around-span-elements-with-python-regex/69792309#69792309

**Comment by tylerecouture** [comment]
Argh... I just can't reproduce this problem.  I know it happens sometimes, but I can't figure out why.  No matter what I try I can't force it to happen.
