### ISSUE TITLE
Prerequisite Campaign

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#890]
Could the prerequisite for a badge be a campaign? 

If a prerequisite was a campaign, it would allow you to change the contents of the campaign and it would automatically reconfigure.

This would be useful when having multiple individual quests that are non-linear such as those in the Inscape Typography campaign that leads to the Inkscape Commander badge. 

It could also be useful if a user wanted to add or remove a quest at the end of a linear campaign.

**Comment by tylerecouture** [comment]
Definitely.  This seems pretty obvious actually, I'm surprised I haven't done it yet.

**Comment by tylerecouture** [comment]
Ok, I know why I hadn't done it yet... the maps are ridiculously complicated to generate =P

**Comment by fjbagley** [comment]
Too bad! Thanks for trying. Perhaps a ByteDeck 2.0 addition?

**Comment by tylerecouture** [comment]
Sorry, this was closed automatically by the commit that solved the issue! It's done and works, I just need to update the production server before its available to use live.

**Comment by fjbagley** [comment]
I tried it out. It works well in the map too. Do you know if this requires much more compute? Would you be able to add this one to the basic prerequisites section?

**Comment by tylerecouture** [comment]
I wasn't planning to put anything more into the basic prereqs section.  The basic prereqs section is just supposed to be a temporary stop-gap measure until we can move the entire pre-req form out of the admin section.
