### ISSUE TITLE
Tag (Competancies) feature

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#909]
Add ability to add tags to quests and badges.

Then the ability to view XP by tag, per student.

For example, a teacher could tag quests and badges with competencies, and then view how much XP each student has earned per competency.

**Comment by tylerecouture** [comment]
django-taggit?

**Comment by tylerecouture** [comment]
related #552

**Comment by 9921622** [comment]
Can I assign myself this issue?

**Comment by tylerecouture** [comment]
This is a fairly advanced issue, but I'm willing to hand it over if you're interested!  I would suggest using the [django-taggit](https://django-taggit.readthedocs.io/en/latest/) addon with [django-auto-complete-light](https://django-autocomplete-light.readthedocs.io/en/master/taggit.html) for the widgets.  I'm thinking of switching from django-select2 (currently we use) to DAL (django-auto-complete-light).  This depends on a few other issues too though.

**Comment by tylerecouture** [comment]
Closing as a duplicate of #960.
