### ISSUE TITLE
Change "Grade" to "Group or Grade" (Request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#919]
Not all users use Grades for decks.
If Grade can be changed to something like Group | Grade... that would help.

**Comment by tylerecouture** [comment]
Yep, I agree.  The use of "grade" in the app is a holdover.  However, it can currently be used as a prerequisite.  I wonder if we should just combine "block" and "grade" into a single field called "group" or "cohort"?

Is it useful to have them both?

**Comment by aluxenburg** [comment]
I don't know about being useful to have both.
I would rather just have "group" and have that a prerequisite.
I don't know what others need.

**Comment by aluxenburg** [comment]
Can you let me know when "Grade" is going to be eliminated... I would like to create a video tutorial for students to create an account and join a course ASAP.  The simpler we can make the sign up process the better... fewer choices, yet still useable by us.

**Comment by tylerecouture** [comment]
I'll try to get that done this week, along with the few remaining Beta release issues that are still unresolved.

**Comment by aluxenburg** [comment]
Sounds good. I am going to stick with my plan of contacting users with the changes this weekend if possible.
Thanks again for all of this work, Tylere. Super.
