### ISSUE TITLE
Campaign XP Subtotals (Feature Request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#922]
We are seeing many educators starting to use skills trees for student metacognition and assessment around competencies.  Very powerful. Campaigns are perfect for combining quests on specific competencies.  An XP subtotal appearing somewhere might be a good way to help teachers and students see progress in specific competencies.

**Comment by tylerecouture** [comment]
Related: #909

**Comment by aluxenburg** [comment]
FYI: A surprising number of my students are interested in this feature request.

**Comment by tylerecouture** [comment]
Can you provide more detail on this one?  Maybe some examples of what specific data would be presented and where it should go?  Thanks!  Also, would this become redundant if a tagging feature was implemented?

**Comment by aluxenburg** [comment]
Yes. This would be redundant if we having tagging and if tagging can be easy to use.

**Comment by tylerecouture** [comment]
linked to #960

**Comment by tylerecouture** [comment]
Consolidating into #960
