### ISSUE TITLE
Image for Ranks (Feature Request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#924]
Once less tech-savvy teachers begin to use ByteDeck, changing the Awesome Fonts in Ranks is going to be a challenge.
If we could use images instead, that might be better for folks. 
Or.. provide an option to see the rank text rather than the icon at the top.

**Comment by tylerecouture** [comment]
Yep, that definitely needs to be more user friendly.

**Comment by tylerecouture** [comment]
New option available to integrate FA with django.  Just need an Icon model field, or a font-awesome widget to go with it:
https://fontawesome.com/docs/web/use-with/python-django
https://github.com/BenjjinF/django-fontawesome-5

**Comment by tylerecouture** [comment]
#492 would solve this.

**Comment by tylerecouture** [comment]
Removing as duplicate of 492
