### ISSUE TITLE
Move prerequisites from the admin site to the front end (Request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#925]
The less new, non-tech-savvy teachers need to do in the Admin site the better.
It scares them.

**Comment by tylerecouture** [comment]
Pretty much  completed, just tidying up the loose ends now:


![image](https://user-images.githubusercontent.com/10604391/173766399-afa10b14-bb05-4807-a0fc-ccbc3a8ee412.png)

**Comment by aluxenburg** [comment]
Awesome.
I am looking forward to having a look.

**Comment by tylerecouture** [comment]
Todo

- [ ] Add existing prerequisites list above the form
- [ ] Somehow indicate the type/model of prereq (Badge, Course, Quest) in the form (already indicated in dropdown when searching, but once selected can't tell)
- [ ] Add link to this form in the prereq section of the Quest form.
- [ ] Add helptext to the fields
