### ISSUE TITLE
Site config option to cap mark percentage at 100%

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#926]
I now have several quests that are repeating quests.  They are not counted in the marks algorithm.
Why not just have marks based on the total XP for a specific course?

**Comment by tylerecouture** [comment]
I'm not sure I understand this one?  XP is currently the sum of all quests (including repeating), badges, and any manual adjustment.

Repeating quests should be counted and I'm not aware of any bugs in that.  More specific details would be helpful to understand this issue.

**Comment by aluxenburg** [comment]
Repeating quests and variable quests do not show up in the totals. I have students with marks of 200% showing up because the total XP it is using for the calculation comes from available quests, rather than the course total XP.

**Comment by tylerecouture** [comment]
Sounds like a possible bug in repeating + variable XP?

Or if you can email me a link to the student's profile, I can investigate and figure out what might be going on.

**Comment by aluxenburg** [comment]
I don't think it is a bug... I think that marks cannot calculate XP from a Quest that does not exist... as it has not repeated, or a quest that has not had variable XP added... how can it... it does not yet exist in the totals.
If marks are determined by total XP, why not just have them based on the total XP for the course as stated in the course configuration?

**Comment by tylerecouture** [comment]
Apologies, I'm struggling to understand this one!

Do you mean the conversion of XP to a %?  If yes, see the Marks Calculation page where that conversion is explicitly explained, and it based on time through the semester.  If you see anything there that seems wrong or unexpected, let me know.

**Comment by aluxenburg** [comment]
Marks Calculation Page?  
Not sure what that is.  I have a marks range page.  I have attached that and have provided a screenshot of student XP to Mark
<img width="216" alt="mark to XP" src="https://user-images.githubusercontent.com/95307054/152581159-48fdc4a9-60a7-424b-8503-c44e61bae085.png">
<img width="658" alt="Mark ranges" src="https://user-images.githubusercontent.com/95307054/152581164-cbbdfaec-104c-4376-8a64-76040f5e7a86.png">
.  I may not be understanding something.

**Comment by aluxenburg** [comment]
Perhaps it is a semester date range issue.  I will make my dates more accurate and see what happens.

**Comment by aluxenburg** [comment]
OK.
I see it now.  Date range needs to be accurate. It improved the numbers.
BUT, students who are well ahead are currently above 100%. Perhaps 100% needs to be a cap so that this is not confusing to the students or the teachers.

**Comment by tylerecouture** [comment]
On any student's profile page click the chart button to see details about how that conversion currently works:
![image](https://user-images.githubusercontent.com/10604391/152583418-5e8402d9-6c9a-410d-9b56-e11a50573785.png)

An option to cap at 100% should be easy to add!

**Comment by aluxenburg** [comment]
I am missing that icon.  I have the other three.

**Comment by tylerecouture** [comment]
Teachers won't have it only students, and only if "Display Marks Calculations Page" is turned on in your Site Config

**Comment by aluxenburg** [comment]
Thank you for updating this and for the write-up.  I will add the writeup to the Tutorial site.
I guess I also need to start adding the tutorials to the GitHub site.

**Comment by aluxenburg** [comment]
Should my student list view reflect this 100% cap... if so... it does not yet.

**Comment by tylerecouture** [comment]
It will when the changes are pushed to the production server, which I
usually do once a week.

**Comment by aluxenburg** [comment]
OK Thanks.
