### ISSUE TITLE
Approved Quest List View Filter (Feature Request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#935]
When viewing the list of folks who have completed a specific quest, It would be good to be able to filter the list by Block or User.

**Comment by tylerecouture** [comment]
@Enprogames did you capture this one in the bootstrap-table conversion?  e.g. /quests/approvals/approved/1/

This might already use one of the templates you've updated.

**Comment by Enprogames** [comment]
> @Enprogames did you capture this one in the bootstrap-table conversion? e.g. /quests/approvals/approved/1/
> 
> This might already use one of the templates you've updated.

@tylerecouture Going to that link on my instance of the site, it appears so!
![image](https://github.com/bytedeck/bytedeck/assets/11304586/31241ce6-7337-407d-bb7a-de582afac562)

Assuming "Block" is the same as "Group" in this context.
