### ISSUE TITLE
Contact Change to Discuss forum may cause confusion

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#943]
Students seeing "Discussion Forum" will think that it is a course-based discussion.
Can we come up with a different name for that in the dropdown? "ByteDeck Forum"?

**Comment by tylerecouture** [comment]
Yep.  I though because it was under the ByteDeck section it would be clear, but maybe not. I will change.

**Comment by tylerecouture** [comment]
Actually, this is in the admin menu, students won't see anything in this menu, it's for teachers/instructors/deck owners only.  Do you still think change is needed?

**Comment by aluxenburg** [comment]
I do , actually.
But that is me

**Comment by aluxenburg** [comment]
Instructors can easily think that this is a course discussion.
