### ISSUE TITLE
Fix "All" button logic in Quest Approvals

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#945]
There is some logic that determines whether the "All" blocks button appears on a teacher's Quest Approvals page.

However, a teacher (`is_staff=True`)  that is not assigned to any Blocks currently doesn't get the button.  They need to get the button!

Need to write tests for this too.

**Comment by 9921622** [comment]
cant seem to get "All" blocks button to show up. Can you send a screenshot of what it looks like?

**Comment by 9921622** [comment]
Can you get a screenshot of "All" blocks button? cant seem to find it

**Comment by tylerecouture** [comment]
Yes, I'll add specific steps to repeat this weekend.

**Comment by tylerecouture** [comment]
1. Create a second steacher/taff account by editing a user in django admin and making is_staff = True
2. Make sure you have at least 2 Blocks.  Assign a teacher (staff) to one block, and the other teacher to the second block.
3. You may need to also create some student accounts and sign them up for courses in each block for this to show, I can't remember
4. Now, when a teacher is signed in they will only see Quest Submission for students that are in a course in their own blocks ("My Blocks"), but an "All" bocks button should appear so they can also view submissions from the other teacher's block:

![image](https://user-images.githubusercontent.com/10604391/170841908-2fbce011-aa64-4ffe-b04e-71044da1e5bd.png)

**Comment by 9921622** [comment]
I cant seem to reproduce. Even if im not in a block i can still see the all button

![image](https://user-images.githubusercontent.com/39788517/171072850-37a25cb8-8c51-480f-b640-227d60c20af7.png)
![image](https://user-images.githubusercontent.com/39788517/171072857-dcc3c270-7336-412a-bbdd-81ebab69b467.png)

**Comment by tylerecouture** [comment]
I couldn't repeat it either, so I'm going to close this.  Can create a  new issue with more details if it comes up again.
