### ISSUE TITLE
Attached Files Spaces Become Underscores

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#949]
When files are attached the blank spaces in the names are replaced with underscores. This has been a minor issue with some users who have put spaces in their css files as the stylesheet href no longer matches up.

**Comment by fjbagley** [comment]
This is a very minor issue, but I thought I'd put it here in case this might affects future users in some unknown way.

**Comment by tylerecouture** [comment]
I've noticed that too.  Suggested solution?  Error message when trying to upload?  Who is teaching these kids to put spaces in file names anyway ;)

**Comment by fjbagley** [comment]
An error message might be worse. Then the question would be why can't this site handle files with spaces in them? It will cause issues for very few people. Perhaps we just let it go?

Who is teaching those kids is actually a tough question to answer: Me? YouTube? Themselves? ByteDeck?

**Comment by tylerecouture** [comment]
I will add help text indicating that spaces in filenames will be replaced with underscores.  It will only ever matter in CSS files because the HTML files have the filename hardcoded in them.  Although really this should probably just go in the quest.

**Comment by tylerecouture** [comment]
Actually, this info should be in the quests. Gonna close this.
