### ISSUE TITLE
link styling bugs on Quest Approvals page

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#952]
This started appear a few days ago, it is only happening for me on the "Quest Approvals" page, no where else:

a tag styling is being over written by what seems to be browser defaults?  All links are turning blue and underline.  Behaviour is a bit different between chrome and Firefox.  I've highlighted some of the problems, but there are more.

Chrome (also light theme, just to make sure it wasn't a theme issue, but problem is same regardless of theme):
![image](https://user-images.githubusercontent.com/10604391/157300246-1df4e1ab-cc2a-4a62-9356-e7e4f4f726ab.png)

Firefox, dark theme
![image](https://user-images.githubusercontent.com/10604391/157300490-57e5d3e1-abe4-4bca-94a2-28e2370386ce.png)

**Comment by aluxenburg** [comment]
I am not seeing this on my Chrome browser.

**Comment by tylerecouture** [comment]
> I am not seeing this on my Chrome browser

**Comment by fjbagley** [comment]
I haven't seen it in Edge either.

**Comment by tylerecouture** [comment]
It's gone, must have been a cache issue.
