### ISSUE TITLE
Video Unavailable Error

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#955]
[This quest](https://studiotyee.bytedeck.com/quests/276/) has a video unavailable error.  

![image](https://user-images.githubusercontent.com/37415548/157385574-0d4d5155-e75b-4da5-a133-318033d61fc9.png)

The video actually is available when the link is clicked.

Possibly related to [this](https://support.google.com/youtube/thread/20562339/getting-video-unavailable-error-on-an-embedded-url?hl=en)?

**Comment by tylerecouture** [comment]
This isn't a Bytedeck issue, maybe post in the Todo list?
