### ISSUE TITLE
quest available outside course and no prereqs doesn't appear for an existing student without a course

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#957]
Related to #936 

Currently the 'update_quest_conditions_all_users()` task only runs on current students currently enrolled in a course.

**prerequisites.tasks.update_quest_conditions_all_users**
```
# only cycle through users currently in a course
    users = CourseStudent.objects.all_users_for_active_semester()
```

But this leaves an edge case hole, because a new user that isn't in a course won't  be able to see any new quests that are created (new quest that has no prereqs and is also available outside of course).

Steps to Reproduce:

1. Create a new student, DON'T join a course
2. As Admin, create a new quest with no prereqs, and also "Available outside course" = True
3. Confirm celery task is received:
```
celery_1       | [2022-03-15 20:01:10,036: INFO/MainProcess] Task prerequisites.tasks.update_quest_conditions_all_users[fc3966b0-a272-45c1-923b-1a70ba75c13e] received
```
4. Wait for celery task is complete
5. Refresh Available Quests on the new user... **quest doesn't show up**
6. Create another new user, that quest appears for them (under the "join a course" button.) because they do a calculation when the account is created.

**Comment by yujinyuz** [comment]
@tylerecouture I'm not quite sure how we want to proceed with this.

Should we just loop through all students instead of just looping through each student that is enrolled?

**Comment by yujinyuz** [comment]
Do you have any idea what this code block is for? Coz it doesn't make sense to me as to what it does and it doesn't have any comment, and the commit message isn't helping as well.
https://github.com/bytedeck/bytedeck/blob/f9987aa8a359bf75bd260692e436b3fc23656b12/src/prerequisites/tasks.py#L149-L151

**Comment by tylerecouture** [comment]
> @tylerecouture I'm not quite sure how we want to proceed with this.
> 
> Should we just loop through all students instead of just looping through each student that is enrolled?

For quests where 'available_outside_of_course' is True, it should cycle through all non-archived users (archived=False)


Currently we only loop through active students (students currently enrolled in a course in the active semester... I think?)

**Comment by tylerecouture** [comment]
I believe this is a recursive call that starts the next "chunk" of users.

It gets the last user id in the list users[-1] and continues the next chunk
with the next user id (+1).

For example if the chunk size if 5 users.

This method will first run
 ‘update_quest_conditions_for_user.apply_async(args=[uid], queue='default')‘

On the first 5 user IDs in the list of users, e.g. user id of 1, 2, 3, 4, 5
(for example.

Then, this code gets the next user id by taking the last id in the list (5)
and adding one (6) and then recursively calling itself starting with user
id =6.

Does that make sense?

Sorry for the poor formatting. I'm trying to reply from my phone.

Would be awesome for you to add some comments to this code.

**Comment by yujinyuz** [comment]
Yeah that makes sense now. Didn't know you could recursively call a celery task. Will add it in the comment
