### ISSUE TITLE
Abitility to tag quests

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#960]
There are many reasons for this:
Many teachers have skill-sets or competencies as outcomes.  Tags are perfect for this.
Teachers and students can view groupings of quests based on tags. Why? Well, one reason: a quest can count in more than one campaign...
Teachers and students can find sub-totals for XP in certain tags, therefore seeing things as a "skills trees" or bar graphs.
...

**Comment by tylerecouture** [comment]
Related #552 and #909

**Comment by tylerecouture** [comment]
Consolidating several duplicate issues into this one:
-  Connecting Learning Outcomes to Quests #552 
- Tag (Competancies) feature #909 
- Campaign XP Subtotals (Feature Request) #922

**Comment by tylerecouture** [comment]
Done.
