### ISSUE TITLE
New decks have no preset badge rarities

### ISSUE THREAD

**Issue by Dylan-RG-Patterson** [bytedeck/bytedeck#981]
![image](https://user-images.githubusercontent.com/105619909/170619912-2d0450a4-2490-4267-bb97-0d5edd5dc35e.png)
badges don't have rarities before they're assigned manually in a new deck.
steal the rarity system from the live hackerspace page and have them automatically generated at the conception of a new deck.
the code for this should be written in tenant/initializations.py.

**Comment by Dylan-RG-Patterson** [comment]
![image](https://user-images.githubusercontent.com/105619909/170620261-b8bc3816-ac02-4f64-b2bc-b15fbad297de.png)
this is also good context

**Comment by tylerecouture** [comment]
Use this for the defaults:
![image](https://user-images.githubusercontent.com/10604391/170621722-ffd1fcb4-00d1-41f7-bee8-1f86213be767.png)
